<?php

/**
 * ConvertText - Allows you to convert text between Flash/Flex htmlText and pure html.
 *
 * @author Jeroen Desloovere <jeroen@siesqo.be>
 */	
class ConvertText
{
	/**
	 * To Flash - so we can use it in a Flash/Flex htmlText field
	 *
	 * @param string $value
	 * @return string
	 */
	public static function toFlash($value)
	{
		$pattern = "/<\/span><\/p>/";
		$value = preg_replace($pattern, "", $value);
		// ZOEK NAAR BREAKRULES DIE ENTERS MOETEN KOMEN
		$pattern = "/<br \/>/";
		$value = preg_replace($pattern, "\n", $value);
		$pattern = "/<\/p>/";
		$value = preg_replace($pattern, "", $value);
		
		$pattern = "/<p style=text-align:left>/";
		$value = preg_replace($pattern, "", $value);
		$pattern = "/<p style=text-align:right>/";
		$value = preg_replace($pattern, "", $value);
		$pattern = "/<p style=text-align:center>/";
		$value = preg_replace($pattern, "", $value);
		$pattern = "/<p style=text-align:justify>/";
		$value = preg_replace($pattern, "", $value);
		$pattern = "/<\/p>/";
		$value = preg_replace($pattern, "", $value);

		$pattern = "/id=(.*?)/";
		$value = preg_replace($pattern, "", $value);
		$pattern = "/style=(.*?)/";
		$value = preg_replace($pattern, "", $value);
		
		$pattern = "/<span id=\"(.*?)\"(.*?)>/";
		$value = preg_replace($pattern, "", $value);
		$pattern = "/<span(.*?)>/";
		$value = preg_replace($pattern, "", $value);
		//$value = preg_replace($pattern, "", $value);           
	   
		$pattern = '/"color:(.*?)"/';
		$value = preg_replace($pattern, "", $value);
		$pattern = '/"font-size:(.*?)px"/';
		$value = preg_replace($pattern, "", $value);
		$pattern = '/"font-family:(.*?)"/';
		$value = preg_replace($pattern, "", $value);
		$pattern = '/"text-align:(.*?)"/';
		$value = preg_replace($pattern, "", $value);

		$pattern = "/<\/li><li>/";
		$value = preg_replace($pattern, "", $value);
		$pattern = "/<\/li><\/ul>/";
		$value = preg_replace($pattern, "", $value);
		$pattern = "/<ul><li>/";
		$value = preg_replace($pattern, "", $value);
		
		$pattern = "/<a href>/";
		$value = preg_replace($pattern, "", $value);
		$pattern = "/<\/a>/";
		$value = preg_replace($pattern, "", $value);
		$pattern = "/target/";
		$value = preg_replace($pattern, "", $value);
		
		$value = preg_replace("/<br>/", "\n", $value);
		$value = preg_replace("/<p>/", "", $value);
		$value = preg_replace("/<p >/", "", $value);
		
		$pattern = "/<em>/";
		$value = preg_replace($pattern, "<i>", $value);
		$pattern = "/<\/em>/";
		$value = preg_replace($pattern, "</i>", $value);
		$pattern = "/<strong>/";
		$value = preg_replace($pattern, "<b>", $value);
		$pattern = "/<\/strong>/";
		$value = preg_replace($pattern, "</b>", $value);
		$pattern = "/<u>/";
		$value = preg_replace($pattern, "<u>", $value);
		$pattern = "/<\/u>/";
		$value = preg_replace($pattern, "</u>", $value);
		/*
		$value = preg_replace("/</", "", $value);
		$value = preg_replace("/>/", "", $value);
		$value = preg_replace("/\//", "", $value);*/

		
		/*
		$value = preg_replace("/<strong/", "", $value);
		//$value = preg_replace("/<span/", "", $value);
		
		$value = preg_replace("/<italic/", "", $value);
		$value = preg_replace("/<underline/", "", $value);
		*/
		
		// SPECIALE KARAKTERS TERUGPLAATSEN
		$pattern = "/&#193;/";
		$value = preg_replace($pattern, "Á", $value);
		$pattern = "/&#225;/";
		$value = preg_replace($pattern, "á", $value);
		$pattern = "/&#226;/";
		$value = preg_replace($pattern, "â", $value);
		$pattern = "/&#194;/";
		$value = preg_replace($pattern, "Â", $value);
		$pattern = "/&#180;/";
		$value = preg_replace($pattern, "´", $value);
		$pattern = "/&#230;/";
		$value = preg_replace($pattern, "æ", $value);
		$pattern = "/&#198;/";
		$value = preg_replace($pattern, "Æ", $value);
		$pattern = "/&#192;/";
		$value = preg_replace($pattern, "À", $value);
		$pattern = "/&#224;/";
		$value = preg_replace($pattern, "à", $value);
		$pattern = "/&#913;/";
		$value = preg_replace($pattern, "Α", $value);
		$pattern = "/&#945;/";
		$value = preg_replace($pattern, "α", $value);
		/*$pattern = "/&#38;/";
		$value = preg_replace($pattern, "&", $value);*/
		$pattern = "/&#229;/";
		$value = preg_replace($pattern, "å", $value);
		$pattern = "/&#197;/";
		$value = preg_replace($pattern, "Å", $value);
		$pattern = "/&#8776;/";
		$value = preg_replace($pattern, "≈", $value);
		$pattern = "/&#195;/";
		$value = preg_replace($pattern, "Ã", $value);
		$pattern = "/&#227;/";
		$value = preg_replace($pattern, "ã", $value);
		$pattern = "/&#196;/";
		$value = preg_replace($pattern, "Ä", $value);
		$pattern = "/&#228;/";
		$value = preg_replace($pattern, "ä", $value);
		$pattern = "/&#8222;/";
		$value = preg_replace($pattern, "„", $value);
		$pattern = "/&#914;/";
		$value = preg_replace($pattern, "Β", $value);
		$pattern = "/&#946;/";
		$value = preg_replace($pattern, "β", $value);
		$pattern = "/&#166;/";
		$value = preg_replace($pattern, "¦", $value);
		$pattern = "/&#8226;/";
		$value = preg_replace($pattern, "•", $value);
		$pattern = "/&#8745;/";
		$value = preg_replace($pattern, "∩", $value);
		$pattern = "/&#199;/";
		$value = preg_replace($pattern, "Ç", $value);
		$pattern = "/&#231;/";
		$value = preg_replace($pattern, "ç", $value);
		$pattern = "/&ccedil/";
		$value = preg_replace($pattern, "&#231;", $value);
		$pattern = "/&#184;/";
		$value = preg_replace($pattern, "¸", $value);
		$pattern = "/&#162;/";
		$value = preg_replace($pattern, "¢", $value);
		$pattern = "/&#967;/";
		$value = preg_replace($pattern, "χ", $value);
		$pattern = "/&#935;/";
		$value = preg_replace($pattern, "Χ", $value);
		$pattern = "/&#710;/";
		$value = preg_replace($pattern, "ˆ", $value);
		$pattern = "/&#9827;/";
		$value = preg_replace($pattern, "♣", $value);
		$pattern = "/&#8773;/";
		$value = preg_replace($pattern, "≅", $value);
		$pattern = "/&#169;/";
		$value = preg_replace($pattern, "©", $value);
		$pattern = "/&#8629;/";
		$value = preg_replace($pattern, "↵", $value);
		$pattern = "/&#8746;/";
		$value = preg_replace($pattern, "∪", $value);
		$pattern = "/&#164;/";
		$value = preg_replace($pattern, "¤", $value);
		$pattern = "/&#8224;/";
		$value = preg_replace($pattern, "†", $value);
		$pattern = "/&#8225;/";
		$value = preg_replace($pattern, "‡", $value);
		$pattern = "/&#8659;/";
		$value = preg_replace($pattern, "⇓", $value);
		$pattern = "/&#8595;/";
		$value = preg_replace($pattern, "↓", $value);
		$pattern = "/&#176;/";
		$value = preg_replace($pattern, "°", $value);
		$pattern = "/&#916;/";
		$value = preg_replace($pattern, "Δ", $value);
		$pattern = "/&#948;/";
		$value = preg_replace($pattern, "δ", $value);
		$pattern = "/&#9830;/";
		$value = preg_replace($pattern, "♦", $value);
		$pattern = "/&#247;/";
		$value = preg_replace($pattern, "÷", $value);
		$pattern = "/&#233;/";
		$value = preg_replace($pattern, "é", $value);
		$pattern = "/&#201;/";
		$value = preg_replace($pattern, "É", $value);
		$pattern = "/&#202;/";
		$value = preg_replace($pattern, "Ê", $value);
		$pattern = "/&#234;/";
		$value = preg_replace($pattern, "ê", $value);
		$pattern = "/&#232;/";
		$value = preg_replace($pattern, "è", $value);
		$pattern = "/&#200;/";
		$value = preg_replace($pattern, "È", $value);
		$pattern = "/&#8709;/";
		$value = preg_replace($pattern, "∅", $value);
		$pattern = "/&#949;/";
		$value = preg_replace($pattern, "ε", $value);
		$pattern = "/&#917;/";
		$value = preg_replace($pattern, "Ε", $value);
		$pattern = "/&#8801;/";
		$value = preg_replace($pattern, "≡", $value);
		$pattern = "/&#919;/";
		$value = preg_replace($pattern, "Η", $value);
		$pattern = "/&#951;/";
		$value = preg_replace($pattern, "η", $value);
		$pattern = "/&#240;/";
		$value = preg_replace($pattern, "ð", $value);
		$pattern = "/&#208;/";
		$value = preg_replace($pattern, "Ð", $value);
		$pattern = "/&#235;/";
		$value = preg_replace($pattern, "ë", $value);
		$pattern = "/&#203;/";
		$value = preg_replace($pattern, "Ë", $value);
		$pattern = "/&#8364;/";
		$value = preg_replace($pattern, "€", $value);
		$pattern = "/&#8707;/";
		$value = preg_replace($pattern, "∃", $value);
		$pattern = "/&#402;/";
		$value = preg_replace($pattern, "ƒ", $value);
		$pattern = "/&#8704;/";
		$value = preg_replace($pattern, "∀", $value);
		$pattern = "/&#189;/";
		$value = preg_replace($pattern, "½", $value);
		$pattern = "/&#188;/";
		$value = preg_replace($pattern, "¼", $value);
		$pattern = "/&#190;/";
		$value = preg_replace($pattern, "¾", $value);
		$pattern = "/&#8260;/";
		$value = preg_replace($pattern, "⁄", $value);
		$pattern = "/&#915;/";
		$value = preg_replace($pattern, "Γ", $value);
		$pattern = "/&#947;/";
		$value = preg_replace($pattern, "γ", $value);
		$pattern = "/&#8805;/";
		$value = preg_replace($pattern, "≥", $value);
		$pattern = "/&#62;/";
		$value = preg_replace($pattern, ">", $value);
		$pattern = "/&#8660;/";
		$value = preg_replace($pattern, "⇔", $value);
		$pattern = "/&#8596;/";
		$value = preg_replace($pattern, "↔", $value);
		$pattern = "/&#9829;/";
		$value = preg_replace($pattern, "♥", $value);
		$pattern = "/&#8230;/";
		$value = preg_replace($pattern, "…", $value);
		$pattern = "/&#237;/";
		$value = preg_replace($pattern, "í", $value);
		$pattern = "/&#205;/";
		$value = preg_replace($pattern, "Í", $value);
		$pattern = "/&#238;/";
		$value = preg_replace($pattern, "î", $value);
		$pattern = "/&#206;/";
		$value = preg_replace($pattern, "Î", $value);
		$pattern = "/&#161;/";
		$value = preg_replace($pattern, "¡", $value);
		$pattern = "/&#204;/";
		$value = preg_replace($pattern, "Ì", $value);
		$pattern = "/&#236;/";
		$value = preg_replace($pattern, "ì", $value);
		$pattern = "/&#8734;/";
		$value = preg_replace($pattern, "∞", $value);
		$pattern = "/&#8747;/";
		$value = preg_replace($pattern, "∫", $value);
		$pattern = "/&#921;/";
		$value = preg_replace($pattern, "Ι", $value);
		$pattern = "/&#953;/";
		$value = preg_replace($pattern, "ι", $value);
		$pattern = "/&#191;/";
		$value = preg_replace($pattern, "¿", $value);
		$pattern = "/&#8712;/";
		$value = preg_replace($pattern, "∈", $value);
		$pattern = "/&#207;/";
		$value = preg_replace($pattern, "Ï", $value);
		$pattern = "/&#239;/";
		$value = preg_replace($pattern, "ï", $value);
		$pattern = "/&#922;/";
		$value = preg_replace($pattern, "Κ", $value);
		$pattern = "/&#954;/";
		$value = preg_replace($pattern, "κ", $value);
		$pattern = "/&#955;/";
		$value = preg_replace($pattern, "λ", $value);
		$pattern = "/&#923;/";
		$value = preg_replace($pattern, "Λ", $value);
		$pattern = "/&#9001;/";
		$value = preg_replace($pattern, "〈", $value);
		$pattern = "/&#171;/";
		$value = preg_replace($pattern, "«", $value);
		$pattern = "/&#8592;/";
		$value = preg_replace($pattern, "←", $value);
		$pattern = "/&#8656;/";
		$value = preg_replace($pattern, "⇐", $value);
		$pattern = "/&#8968;/";
		$value = preg_replace($pattern, "⌈", $value);
		$pattern = "/&#8220;/";
		$value = preg_replace($pattern, "“", $value);
		$pattern = "/&#8804;/";
		$value = preg_replace($pattern, "≤", $value);
		$pattern = "/&#8970;/";
		$value = preg_replace($pattern, "⌊", $value);
		$pattern = "/&#8727;/";
		$value = preg_replace($pattern, "∗", $value);
		$pattern = "/&#8974;/";
		$value = preg_replace($pattern, "◊", $value);
		$pattern = "/&#8249;/";
		$value = preg_replace($pattern, "‹", $value);
		$pattern = "/&#8216;/";
		$value = preg_replace($pattern, "‘", $value);
		$pattern = "/&#60;/";
		$value = preg_replace($pattern, "<", $value);
		$pattern = "/&#175;/";
		$value = preg_replace($pattern, "¯", $value);
		$pattern = "/&#8212;/";
		$value = preg_replace($pattern, "—", $value);
		$pattern = "/&#181;/";
		$value = preg_replace($pattern, "µ", $value);
		$pattern = "/&#183;/";
		$value = preg_replace($pattern, "·", $value);
		$pattern = "/&#8722;/";
		$value = preg_replace($pattern, "−", $value);
		$pattern = "/&#924;/";
		$value = preg_replace($pattern, "Μ", $value);
		$pattern = "/&#956;/";
		$value = preg_replace($pattern, "μ", $value);
		$pattern = "/&#8711;/";
		$value = preg_replace($pattern, "∇", $value);
		$pattern = "/&#8211;/";
		$value = preg_replace($pattern, "–", $value);
		$pattern = "/&#8800;/";
		$value = preg_replace($pattern, "≠", $value);
		$pattern = "/&#8715;/";
		$value = preg_replace($pattern, "∋", $value);
		$pattern = "/&#172;/";
		$value = preg_replace($pattern, "¬", $value);
		$pattern = "/&#8713;/";
		$value = preg_replace($pattern, "∉", $value);
		$pattern = "/&#8836;/";
		$value = preg_replace($pattern, "⊄", $value);
		$pattern = "/&#241;/";
		$value = preg_replace($pattern, "ñ", $value);
		$pattern = "/&#209;/";
		$value = preg_replace($pattern, "Ñ", $value);
		$pattern = "/&#925;/";
		$value = preg_replace($pattern, "Ν", $value);
		$pattern = "/&#957;/";
		$value = preg_replace($pattern, "ν", $value);
		$pattern = "/&#243;/";
		$value = preg_replace($pattern, "ó", $value);
		$pattern = "/&#211;/";
		$value = preg_replace($pattern, "Ó", $value);
		$pattern = "/&#212;/";
		$value = preg_replace($pattern, "Ô", $value);
		$pattern = "/&#244;/";
		$value = preg_replace($pattern, "ô", $value);
		$pattern = "/&#338;/";
		$value = preg_replace($pattern, "Œ", $value);
		$pattern = "/&#339;/";
		$value = preg_replace($pattern, "œ", $value);
		$pattern = "/&#242;/";
		$value = preg_replace($pattern, "ò", $value);
		$pattern = "/&#210;/";
		$value = preg_replace($pattern, "Ò", $value);
		$pattern = "/&#8254;/";
		$value = preg_replace($pattern, "‾", $value);
		$pattern = "/&#969;/";
		$value = preg_replace($pattern, "ω", $value);
		$pattern = "/&#937;/";
		$value = preg_replace($pattern, "Ω", $value);
		$pattern = "/&#927;/";
		$value = preg_replace($pattern, "Ο", $value);
		$pattern = "/&#959;/";
		$value = preg_replace($pattern, "ο", $value);
		$pattern = "/&#8853;/";
		$value = preg_replace($pattern, "⊕", $value);
		$pattern = "/&#8744;/";
		$value = preg_replace($pattern, "∨", $value);
		$pattern = "/&#170;/";
		$value = preg_replace($pattern, "ª", $value);
		$pattern = "/&#186;/";
		$value = preg_replace($pattern, "º", $value);
		$pattern = "/&#216;/";
		$value = preg_replace($pattern, "Ø", $value);
		$pattern = "/&#248;/";
		$value = preg_replace($pattern, "ø", $value);
		$pattern = "/&#213;/";
		$value = preg_replace($pattern, "Õ", $value);
		$pattern = "/&#245;/";
		$value = preg_replace($pattern, "õ", $value);
		$pattern = "/&#8855;/";
		$value = preg_replace($pattern, "⊗", $value);
		$pattern = "/&#214;/";
		$value = preg_replace($pattern, "Ö", $value);
		$pattern = "/&#246;/";
		$value = preg_replace($pattern, "ö", $value);
		$pattern = "/&#182;/";
		$value = preg_replace($pattern, "¶", $value);
		$pattern = "/&#8706;/";
		$value = preg_replace($pattern, "∂", $value);
		$pattern = "/&#8240;/";
		$value = preg_replace($pattern, "‰", $value);
		$pattern = "/&#8869;/";
		$value = preg_replace($pattern, "⊥", $value);
		$pattern = "/&#966;/";
		$value = preg_replace($pattern, "φ", $value);
		$pattern = "/&#934;/";
		$value = preg_replace($pattern, "Φ", $value);
		$pattern = "/&#928;/";
		$value = preg_replace($pattern, "Π", $value);
		$pattern = "/&#960;/";
		$value = preg_replace($pattern, "π", $value);
		$pattern = "/&#982;/";
		$value = preg_replace($pattern, "ϖ", $value);
		$pattern = "/&#177;/";
		$value = preg_replace($pattern, "±", $value);
		$pattern = "/&#163;/";
		$value = preg_replace($pattern, "£", $value);
		$pattern = "/&#8243;/";
		$value = preg_replace($pattern, "″", $value);
		$pattern = "/&#8242;/";
		$value = preg_replace($pattern, "′", $value);
		$pattern = "/&#8719;/";
		$value = preg_replace($pattern, "∏", $value);
		$pattern = "/&#8733;/";
		$value = preg_replace($pattern, "∝", $value);
		$pattern = "/&#968;/";
		$value = preg_replace($pattern, "ψ", $value);
		$pattern = "/&#936;/";
		$value = preg_replace($pattern, "Ψ", $value);
		//$pattern = "/&#34;/g;//$value = preg_replace($pattern, """, $value);
		$pattern = "/&#8730;/";
		$value = preg_replace($pattern, "√", $value);
		$pattern = "/&#9002;/";
		$value = preg_replace($pattern, "〉", $value);
		$pattern = "/&#187;/";
		$value = preg_replace($pattern, "»", $value);
		$pattern = "/&#8658;/";
		$value = preg_replace($pattern, "⇒", $value);
		$pattern = "/&#8594;/";
		$value = preg_replace($pattern, "→", $value);
		$pattern = "/&#8969;/";
		$value = preg_replace($pattern, "⌉", $value);
		$pattern = "/&#8221;/";
		$value = preg_replace($pattern, "”", $value);
		$pattern = "/&#8476;/";
		$value = preg_replace($pattern, "ℜ", $value);
		$pattern = "/&#174;/";
		$value = preg_replace($pattern, "®", $value);
		$pattern = "/&#8971;/";
		$value = preg_replace($pattern, "⌋", $value);
		$pattern = "/&#929;/";
		$value = preg_replace($pattern, "Ρ", $value);
		$pattern = "/&#961;/";
		$value = preg_replace($pattern, "ρ", $value);
		$pattern = "/&#8250;/";
		$value = preg_replace($pattern, "›", $value);
		$pattern = "/&#8217;/";
		$value = preg_replace($pattern, "’", $value);
		$pattern = "/&#8218;/";
		$value = preg_replace($pattern, "‚", $value);
		$pattern = "/&#352;/";
		$value = preg_replace($pattern, "Š", $value);
		$pattern = "/&#353;/";
		$value = preg_replace($pattern, "š", $value);
		$pattern = "/&#8901;/";
		$value = preg_replace($pattern, "⋅", $value);
		$pattern = "/&#167;/";
		$value = preg_replace($pattern, "§", $value);
		$pattern = "/&#173;/";
		$value = preg_replace($pattern, "­", $value);
		$pattern = "/&#931;/";
		$value = preg_replace($pattern, "Σ", $value);
		$pattern = "/&#963;/";
		$value = preg_replace($pattern, "σ", $value);
		$pattern = "/&#962;/";
		$value = preg_replace($pattern, "ς", $value);
		$pattern = "/&#8764;/";
		$value = preg_replace($pattern, "∼", $value);
		$pattern = "/&#9824;/";
		$value = preg_replace($pattern, "♠", $value);
		$pattern = "/&#8834;/";
		$value = preg_replace($pattern, "⊂", $value);
		$pattern = "/&#8838;/";
		$value = preg_replace($pattern, "⊆", $value);
		$pattern = "/&#8721;/";
		$value = preg_replace($pattern, "∑", $value);
		$pattern = "/&#8835;/";
		$value = preg_replace($pattern, "⊃", $value);
		$pattern = "/&#185;/";
		$value = preg_replace($pattern, "¹", $value);
		$pattern = "/&#178;/";
		$value = preg_replace($pattern, "²", $value);
		$pattern = "/&#179;/";
		$value = preg_replace($pattern, "³", $value);
		$pattern = "/&#8839;/";
		$value = preg_replace($pattern, "⊇", $value);
		$pattern = "/&#223;/";
		$value = preg_replace($pattern, "ß", $value);
		$pattern = "/&#932;/";
		$value = preg_replace($pattern, "Τ", $value);
		$pattern = "/&#964;/";
		$value = preg_replace($pattern, "τ", $value);
		$pattern = "/&#8756;/";
		$value = preg_replace($pattern, "∴", $value);
		$pattern = "/&#920;/";
		$value = preg_replace($pattern, "Θ", $value);
		$pattern = "/&#952;/";
		$value = preg_replace($pattern, "θ", $value);
		$pattern = "/&#977;/";
		$value = preg_replace($pattern, "ϑ", $value);
		$pattern = "/&#222;/";
		$value = preg_replace($pattern, "Þ", $value);
		$pattern = "/&#254;/";
		$value = preg_replace($pattern, "þ", $value);
		$pattern = "/&#732;/";
		$value = preg_replace($pattern, "˜", $value);
		$pattern = "/&#215;/";
		$value = preg_replace($pattern, "×", $value);
		$pattern = "/&#8482;/";
		$value = preg_replace($pattern, "™", $value);
		$pattern = "/&#250;/";
		$value = preg_replace($pattern, "ú", $value);
		$pattern = "/&#218;/";
		$value = preg_replace($pattern, "Ú", $value);
		$pattern = "/&#8657;/";
		$value = preg_replace($pattern, "⇑", $value);
		$pattern = "/&#8593;/";
		$value = preg_replace($pattern, "↑", $value);
		$pattern = "/&#251;/";
		$value = preg_replace($pattern, "û", $value);
		$pattern = "/&#219;/";
		$value = preg_replace($pattern, "Û", $value);
		$pattern = "/&#217;/";
		$value = preg_replace($pattern, "Ù", $value);
		$pattern = "/&#249;/";
		$value = preg_replace($pattern, "ù", $value);
		$pattern = "/&#168;/";
		$value = preg_replace($pattern, "¨", $value);
		$pattern = "/&#978;/";
		$value = preg_replace($pattern, "ϒ", $value);
		$pattern = "/&#965;/";
		$value = preg_replace($pattern, "υ", $value);
		$pattern = "/&#933;/";
		$value = preg_replace($pattern, "Υ", $value);
		$pattern = "/&#252;/";
		$value = preg_replace($pattern, "ü", $value);
		$pattern = "/&#220;/";
		$value = preg_replace($pattern, "Ü", $value);
		$pattern = "/&#8472;/";
		$value = preg_replace($pattern, "℘", $value);
		$pattern = "/&#958;/";
		$value = preg_replace($pattern, "ξ", $value);
		$pattern = "/&#926;/";
		$value = preg_replace($pattern, "Ξ", $value);
		$pattern = "/&#253;/";
		$value = preg_replace($pattern, "ý", $value);
		$pattern = "/&#221;/";
		$value = preg_replace($pattern, "Ý", $value);
		$pattern = "/&#165;/";
		$value = preg_replace($pattern, "¥", $value);
		$pattern = "/&#255;/";
		$value = preg_replace($pattern, "ÿ", $value);
		$pattern = "/&#376;/";
		$value = preg_replace($pattern, "Ÿ", $value);
		$pattern = "/&#918;/";
		$value = preg_replace($pattern, "Ζ", $value);
		$pattern = "/&#950;/";
		$value = preg_replace($pattern, "ζ", $value);
		
		// unclean ...
		$pattern = "/\.\.\./";
		$value = preg_replace($pattern, "...", $value);		   	
		
		// Remove extra white spaces
		$pattern = "/&#8195;&#8195;/";
		$value = preg_replace($pattern, "  ", $value);
		$pattern = "/&#8195;\ /";
		$value = preg_replace($pattern, "  ", $value);
		$pattern = "/&#8195;/";
		$value = preg_replace($pattern, " ", $value);
		$pattern = "/\ &nbsp;/";
		$value = preg_replace($pattern, "  ", $value);
		$pattern = "/&nbsp;\ /";
		$value = preg_replace($pattern, "  ", $value);
		$pattern = "/\ &#8195;/";
		$value = preg_replace($pattern, "  ", $value);
		$pattern = "/\  /";
		$value = preg_replace($pattern, "  ", $value);
		
		// trademark, copyright, ...
		$pattern = "/&trade;/";    
		$value = preg_replace($pattern, "(tm)", $value);
		$pattern = "/&copy;/";    
		$value = preg_replace($pattern, "(c)", $value);
		$pattern = "/&reg;/";    
		$value = preg_replace($pattern, "(r)", $value);
		
		// apo$valueof
		$pattern = "/&#39;/";
		$value = preg_replace($pattern, "'", $value);
		
		// kijk en verwijder 1 spatie indien nodig
		if(preg_match("/ /", $value)){
			$value=ltrim($value);
		}

		return $value;
	}

	/**
	 * To HTML
	 *
	 * @param string $value
	 */
	public static function toHtml($value)
	{
		// ZOEK NAAR ENTERS DIE BREAKRULES MOETEN KOMEN
		$value = preg_replace("/<\/FONT><\/P><\/TEXTFORMAT><TEXTFORMAT(.*?)><P(.*?)><FONT(.*?)>(.*?)/", "<br />", $value);
		$pattern = "/<\/FONT><\/P><\/TEXTFORMAT><TEXTFORMAT(.*?)><P(.*?)><FONT(.*?)><\/FONT><\/P><\/TEXTFORMAT><TEXTFORMAT(.*?)><P(.*?)><FONT(.*?)>(.*?)/";
		$value = preg_replace($pattern, "</p><p>", $value);

		// FLASH / FLEX GERELATEERDE TEKENS
		$pattern = "/<TEXTFORMAT.*?>/";
		$value = preg_replace($pattern, "", $value);
		$pattern = "/<\/TEXTFORMAT.*?>/";
		$value = preg_replace($pattern, "", $value);
		
		$pattern = "/<P ALIGN='LEFT'>/";
		$value = preg_replace($pattern, "<p style=\'text-align:left\'>", $value);
		$pattern = "/<P ALIGN='RIGHT'>/";
		$value = preg_replace($pattern, "<p style=\'text-align:right\'>", $value);
		$pattern = "/<P ALIGN='CENTER'>/";
		$value = preg_replace($pattern, "<p style=\'text-align:center\'>", $value);
		$pattern = "/<P ALIGN='JUSTIFY'>/";
		$value = preg_replace($pattern, "<p style=\'text-align:justify\'>", $value);
		$pattern = "/<\/P>/";
		$value = preg_replace($pattern, "</p>", $value);
		
		$pattern = "/<FONT ID='(.*?)'>/";
		$value = preg_replace($pattern, "<span id=\'$1\'>", $value);
		
		$pattern = "/<FONT(.*?)>/";
		$value = preg_replace($pattern, "<span style=\'\'>", $value);
		//$value = preg_replace($pattern, "<span style=\'$1\'>", $value);
		
		$pattern = "/COLOR=\'(.*?)\'/";
		$value = preg_replace($pattern, "", $value);
		//$value = preg_replace($pattern, "color:$1", $value);
		
		$pattern = "/SIZE=\'(.*?)\'/";
		$value = preg_replace($pattern, "", $value);
		// $value = preg_replace($pattern, "font-size:$1px", $value);
		
		$pattern = "/FACE=\'(.*?)\'/";
		$value = preg_replace($pattern, "", $value);
		// $value = preg_replace($pattern, "font-family:$1", $value);
		
		$pattern = "/ALIGN=\'(.*?)\'/";
		//$value = preg_replace($pattern, "", $value);
		$value = preg_replace($pattern, "text-align:$1", $value);
		
		$pattern = "/LETTERSPACING=\'.*?\'/";
		$value = preg_replace($pattern, "", $value);
		
		$pattern = "/KERNING=\'.*?\'/";
		$value = preg_replace($pattern, "", $value);
		
		$pattern = "/<\/FONT.*?>/";
		$value = preg_replace($pattern, "</span>", $value);
		
		$pattern = "/<\/LI><LI>/";
		$value = preg_replace($pattern, "</li><li>", $value);
		$pattern = "/<\/LI>/";
		$value = preg_replace($pattern, "</li></ul>", $value);
		$pattern = "/<LI>/";
		$value = preg_replace($pattern, "<ul><li>", $value);
		
		$pattern = "/<I>/";
		$value = preg_replace($pattern, "<em>", $value);
		$pattern = "/<\/I>/";
		$value = preg_replace($pattern, "</em>", $value);
		$pattern = "/<B>/";
		$value = preg_replace($pattern, "<$valueong>", $value);
		$pattern = "/<\/B>/";
		$value = preg_replace($pattern, "<$valueong>", $value);
		$pattern = "/<U>/";
		$value = preg_replace($pattern, "<u>", $value);
		$pattern = "/<\/U>/";
		$value = preg_replace($pattern, "</u>", $value);
		
		$pattern = "/<A HREF/";
		$value = preg_replace($pattern, "<a href", $value);
		$pattern = "/<\/A>/";
		$value = preg_replace($pattern, "</a>", $value);
		$pattern = "/TARGET/";
		$value = preg_replace($pattern, "target", $value);
		
		return self::char($value, $value);
	}

	/**
	 * Unchar
	 *
	 * @param string $value
	 */
	public static function unchar($value)
	{
		// SPECIALE KARAKTERS TERUGPLAATSEN
		$pattern = "/&#193;/";
		$value = preg_replace($pattern, "Á", $value);
		$pattern = "/&#225;/";
		$value = preg_replace($pattern, "á", $value);
		$pattern = "/&#226;/";
		$value = preg_replace($pattern, "â", $value);
		$pattern = "/&#194;/";
		$value = preg_replace($pattern, "Â", $value);
		$pattern = "/&#180;/";
		$value = preg_replace($pattern, "´", $value);
		$pattern = "/&#230;/";
		$value = preg_replace($pattern, "æ", $value);
		$pattern = "/&#198;/";
		$value = preg_replace($pattern, "Æ", $value);
		$pattern = "/&#192;/";
		$value = preg_replace($pattern, "À", $value);
		$pattern = "/&#224;/";
		$value = preg_replace($pattern, "à", $value);
		$pattern = "/&#913;/";
		$value = preg_replace($pattern, "Α", $value);
		$pattern = "/&#945;/";
		$value = preg_replace($pattern, "α", $value);
		/*$pattern = "/&#38;/";
		$value = preg_replace($pattern, "&", $value);*/
		$pattern = "/&#229;/";
		$value = preg_replace($pattern, "å", $value);
		$pattern = "/&#197;/";
		$value = preg_replace($pattern, "Å", $value);
		$pattern = "/&#8776;/";
		$value = preg_replace($pattern, "≈", $value);
		$pattern = "/&#195;/";
		$value = preg_replace($pattern, "Ã", $value);
		$pattern = "/&#227;/";
		$value = preg_replace($pattern, "ã", $value);
		$pattern = "/&#196;/";
		$value = preg_replace($pattern, "Ä", $value);
		$pattern = "/&#228;/";
		$value = preg_replace($pattern, "ä", $value);
		$pattern = "/&#8222;/";
		$value = preg_replace($pattern, "„", $value);
		$pattern = "/&#914;/";
		$value = preg_replace($pattern, "Β", $value);
		$pattern = "/&#946;/";
		$value = preg_replace($pattern, "β", $value);
		$pattern = "/&#166;/";
		$value = preg_replace($pattern, "¦", $value);
		$pattern = "/&#8226;/";
		$value = preg_replace($pattern, "•", $value);
		$pattern = "/&#8745;/";
		$value = preg_replace($pattern, "∩", $value);
		$pattern = "/&#199;/";
		$value = preg_replace($pattern, "Ç", $value);
		$pattern = "/&#231;/";
		$value = preg_replace($pattern, "ç", $value);
		$pattern = "/&#184;/";
		$value = preg_replace($pattern, "¸", $value);
		$pattern = "/&#162;/";
		$value = preg_replace($pattern, "¢", $value);
		$pattern = "/&#967;/";
		$value = preg_replace($pattern, "χ", $value);
		$pattern = "/&#935;/";
		$value = preg_replace($pattern, "Χ", $value);
		$pattern = "/&#710;/";
		$value = preg_replace($pattern, "ˆ", $value);
		$pattern = "/&#9827;/";
		$value = preg_replace($pattern, "♣", $value);
		$pattern = "/&#8773;/";
		$value = preg_replace($pattern, "≅", $value);
		$pattern = "/&#169;/";
		$value = preg_replace($pattern, "©", $value);
		$pattern = "/&#8629;/";
		$value = preg_replace($pattern, "↵", $value);
		$pattern = "/&#8746;/";
		$value = preg_replace($pattern, "∪", $value);
		$pattern = "/&#164;/";
		$value = preg_replace($pattern, "¤", $value);
		$pattern = "/&#8224;/";
		$value = preg_replace($pattern, "†", $value);
		$pattern = "/&#8225;/";
		$value = preg_replace($pattern, "‡", $value);
		$pattern = "/&#8659;/";
		$value = preg_replace($pattern, "⇓", $value);
		$pattern = "/&#8595;/";
		$value = preg_replace($pattern, "↓", $value);
		$pattern = "/&#176;/";
		$value = preg_replace($pattern, "°", $value);
		$pattern = "/&#916;/";
		$value = preg_replace($pattern, "Δ", $value);
		$pattern = "/&#948;/";
		$value = preg_replace($pattern, "δ", $value);
		$pattern = "/&#9830;/";
		$value = preg_replace($pattern, "♦", $value);
		$pattern = "/&#247;/";
		$value = preg_replace($pattern, "÷", $value);
		$pattern = "/&#233;/";
		$value = preg_replace($pattern, "é", $value);
		$pattern = "/&#201;/";
		$value = preg_replace($pattern, "É", $value);
		$pattern = "/&#202;/";
		$value = preg_replace($pattern, "Ê", $value);
		$pattern = "/&#234;/";
		$value = preg_replace($pattern, "ê", $value);
		$pattern = "/&#232;/";
		$value = preg_replace($pattern, "è", $value);
		$pattern = "/&#200;/";
		$value = preg_replace($pattern, "È", $value);
		$pattern = "/&#8709;/";
		$value = preg_replace($pattern, "∅", $value);
		$pattern = "/&#949;/";
		$value = preg_replace($pattern, "ε", $value);
		$pattern = "/&#917;/";
		$value = preg_replace($pattern, "Ε", $value);
		$pattern = "/&#8801;/";
		$value = preg_replace($pattern, "≡", $value);
		$pattern = "/&#919;/";
		$value = preg_replace($pattern, "Η", $value);
		$pattern = "/&#951;/";
		$value = preg_replace($pattern, "η", $value);
		$pattern = "/&#240;/";
		$value = preg_replace($pattern, "ð", $value);
		$pattern = "/&#208;/";
		$value = preg_replace($pattern, "Ð", $value);
		$pattern = "/&#235;/";
		$value = preg_replace($pattern, "ë", $value);
		$pattern = "/&#203;/";
		$value = preg_replace($pattern, "Ë", $value);
		$pattern = "/&#8364;/";
		$value = preg_replace($pattern, "€", $value);
		$pattern = "/&#8707;/";
		$value = preg_replace($pattern, "∃", $value);
		$pattern = "/&#402;/";
		$value = preg_replace($pattern, "ƒ", $value);
		$pattern = "/&#8704;/";
		$value = preg_replace($pattern, "∀", $value);
		$pattern = "/&#189;/";
		$value = preg_replace($pattern, "½", $value);
		$pattern = "/&#188;/";
		$value = preg_replace($pattern, "¼", $value);
		$pattern = "/&#190;/";
		$value = preg_replace($pattern, "¾", $value);
		$pattern = "/&#8260;/";
		$value = preg_replace($pattern, "⁄", $value);
		$pattern = "/&#915;/";
		$value = preg_replace($pattern, "Γ", $value);
		$pattern = "/&#947;/";
		$value = preg_replace($pattern, "γ", $value);
		$pattern = "/&#8805;/";
		$value = preg_replace($pattern, "≥", $value);
		$pattern = "/&#62;/";
		$value = preg_replace($pattern, ">", $value);
		$pattern = "/&#8660;/";
		$value = preg_replace($pattern, "⇔", $value);
		$pattern = "/&#8596;/";
		$value = preg_replace($pattern, "↔", $value);
		$pattern = "/&#9829;/";
		$value = preg_replace($pattern, "♥", $value);
		$pattern = "/&#8230;/";
		$value = preg_replace($pattern, "…", $value);
		$pattern = "/&#237;/";
		$value = preg_replace($pattern, "í", $value);
		$pattern = "/&#205;/";
		$value = preg_replace($pattern, "Í", $value);
		$pattern = "/&#238;/";
		$value = preg_replace($pattern, "î", $value);
		$pattern = "/&#206;/";
		$value = preg_replace($pattern, "Î", $value);
		$pattern = "/&#161;/";
		$value = preg_replace($pattern, "¡", $value);
		$pattern = "/&#204;/";
		$value = preg_replace($pattern, "Ì", $value);
		$pattern = "/&#236;/";
		$value = preg_replace($pattern, "ì", $value);
		$pattern = "/&#8734;/";
		$value = preg_replace($pattern, "∞", $value);
		$pattern = "/&#8747;/";
		$value = preg_replace($pattern, "∫", $value);
		$pattern = "/&#921;/";
		$value = preg_replace($pattern, "Ι", $value);
		$pattern = "/&#953;/";
		$value = preg_replace($pattern, "ι", $value);
		$pattern = "/&#191;/";
		$value = preg_replace($pattern, "¿", $value);
		$pattern = "/&#8712;/";
		$value = preg_replace($pattern, "∈", $value);
		$pattern = "/&#207;/";
		$value = preg_replace($pattern, "Ï", $value);
		$pattern = "/&#239;/";
		$value = preg_replace($pattern, "ï", $value);
		$pattern = "/&#922;/";
		$value = preg_replace($pattern, "Κ", $value);
		$pattern = "/&#954;/";
		$value = preg_replace($pattern, "κ", $value);
		$pattern = "/&#955;/";
		$value = preg_replace($pattern, "λ", $value);
		$pattern = "/&#923;/";
		$value = preg_replace($pattern, "Λ", $value);
		$pattern = "/&#9001;/";
		$value = preg_replace($pattern, "〈", $value);
		$pattern = "/&#171;/";
		$value = preg_replace($pattern, "«", $value);
		$pattern = "/&#8592;/";
		$value = preg_replace($pattern, "←", $value);
		$pattern = "/&#8656;/";
		$value = preg_replace($pattern, "⇐", $value);
		$pattern = "/&#8968;/";
		$value = preg_replace($pattern, "⌈", $value);
		$pattern = "/&#8220;/";
		$value = preg_replace($pattern, "“", $value);
		$pattern = "/&#8804;/";
		$value = preg_replace($pattern, "≤", $value);
		$pattern = "/&#8970;/";
		$value = preg_replace($pattern, "⌊", $value);
		$pattern = "/&#8727;/";
		$value = preg_replace($pattern, "∗", $value);
		$pattern = "/&#8974;/";
		$value = preg_replace($pattern, "◊", $value);
		$pattern = "/&#8249;/";
		$value = preg_replace($pattern, "‹", $value);
		$pattern = "/&#8216;/";
		$value = preg_replace($pattern, "‘", $value);
		$pattern = "/&#60;/";
		$value = preg_replace($pattern, "<", $value);
		$pattern = "/&#175;/";
		$value = preg_replace($pattern, "¯", $value);
		$pattern = "/&#8212;/";
		$value = preg_replace($pattern, "—", $value);
		$pattern = "/&#181;/";
		$value = preg_replace($pattern, "µ", $value);
		$pattern = "/&#183;/";
		$value = preg_replace($pattern, "·", $value);
		$pattern = "/&#8722;/";
		$value = preg_replace($pattern, "−", $value);
		$pattern = "/&#924;/";
		$value = preg_replace($pattern, "Μ", $value);
		$pattern = "/&#956;/";
		$value = preg_replace($pattern, "μ", $value);
		$pattern = "/&#8711;/";
		$value = preg_replace($pattern, "∇", $value);
		$pattern = "/&#8211;/";
		$value = preg_replace($pattern, "–", $value);
		$pattern = "/&#8800;/";
		$value = preg_replace($pattern, "≠", $value);
		$pattern = "/&#8715;/";
		$value = preg_replace($pattern, "∋", $value);
		$pattern = "/&#172;/";
		$value = preg_replace($pattern, "¬", $value);
		$pattern = "/&#8713;/";
		$value = preg_replace($pattern, "∉", $value);
		$pattern = "/&#8836;/";
		$value = preg_replace($pattern, "⊄", $value);
		$pattern = "/&#241;/";
		$value = preg_replace($pattern, "ñ", $value);
		$pattern = "/&#209;/";
		$value = preg_replace($pattern, "Ñ", $value);
		$pattern = "/&#925;/";
		$value = preg_replace($pattern, "Ν", $value);
		$pattern = "/&#957;/";
		$value = preg_replace($pattern, "ν", $value);
		$pattern = "/&#243;/";
		$value = preg_replace($pattern, "ó", $value);
		$pattern = "/&#211;/";
		$value = preg_replace($pattern, "Ó", $value);
		$pattern = "/&#212;/";
		$value = preg_replace($pattern, "Ô", $value);
		$pattern = "/&#244;/";
		$value = preg_replace($pattern, "ô", $value);
		$pattern = "/&#338;/";
		$value = preg_replace($pattern, "Œ", $value);
		$pattern = "/&#339;/";
		$value = preg_replace($pattern, "œ", $value);
		$pattern = "/&#242;/";
		$value = preg_replace($pattern, "ò", $value);
		$pattern = "/&#210;/";
		$value = preg_replace($pattern, "Ò", $value);
		$pattern = "/&#8254;/";
		$value = preg_replace($pattern, "‾", $value);
		$pattern = "/&#969;/";
		$value = preg_replace($pattern, "ω", $value);
		$pattern = "/&#937;/";
		$value = preg_replace($pattern, "Ω", $value);
		$pattern = "/&#927;/";
		$value = preg_replace($pattern, "Ο", $value);
		$pattern = "/&#959;/";
		$value = preg_replace($pattern, "ο", $value);
		$pattern = "/&#8853;/";
		$value = preg_replace($pattern, "⊕", $value);
		$pattern = "/&#8744;/";
		$value = preg_replace($pattern, "∨", $value);
		$pattern = "/&#170;/";
		$value = preg_replace($pattern, "ª", $value);
		$pattern = "/&#186;/";
		$value = preg_replace($pattern, "º", $value);
		$pattern = "/&#216;/";
		$value = preg_replace($pattern, "Ø", $value);
		$pattern = "/&#248;/";
		$value = preg_replace($pattern, "ø", $value);
		$pattern = "/&#213;/";
		$value = preg_replace($pattern, "Õ", $value);
		$pattern = "/&#245;/";
		$value = preg_replace($pattern, "õ", $value);
		$pattern = "/&#8855;/";
		$value = preg_replace($pattern, "⊗", $value);
		$pattern = "/&#214;/";
		$value = preg_replace($pattern, "Ö", $value);
		$pattern = "/&#246;/";
		$value = preg_replace($pattern, "ö", $value);
		$pattern = "/&#182;/";
		$value = preg_replace($pattern, "¶", $value);
		$pattern = "/&#8706;/";
		$value = preg_replace($pattern, "∂", $value);
		$pattern = "/&#8240;/";
		$value = preg_replace($pattern, "‰", $value);
		$pattern = "/&#8869;/";
		$value = preg_replace($pattern, "⊥", $value);
		$pattern = "/&#966;/";
		$value = preg_replace($pattern, "φ", $value);
		$pattern = "/&#934;/";
		$value = preg_replace($pattern, "Φ", $value);
		$pattern = "/&#928;/";
		$value = preg_replace($pattern, "Π", $value);
		$pattern = "/&#960;/";
		$value = preg_replace($pattern, "π", $value);
		$pattern = "/&#982;/";
		$value = preg_replace($pattern, "ϖ", $value);
		$pattern = "/&#177;/";
		$value = preg_replace($pattern, "±", $value);
		$pattern = "/&#163;/";
		$value = preg_replace($pattern, "£", $value);
		$pattern = "/&#8243;/";
		$value = preg_replace($pattern, "″", $value);
		$pattern = "/&#8242;/";
		$value = preg_replace($pattern, "′", $value);
		$pattern = "/&#8719;/";
		$value = preg_replace($pattern, "∏", $value);
		$pattern = "/&#8733;/";
		$value = preg_replace($pattern, "∝", $value);
		$pattern = "/&#968;/";
		$value = preg_replace($pattern, "ψ", $value);
		$pattern = "/&#936;/";
		$value = preg_replace($pattern, "Ψ", $value);
		//$pattern = "/&#34;/g;//$value = preg_replace($pattern, """, $value);
		$pattern = "/&#8730;/";
		$value = preg_replace($pattern, "√", $value);
		$pattern = "/&#9002;/";
		$value = preg_replace($pattern, "〉", $value);
		$pattern = "/&#187;/";
		$value = preg_replace($pattern, "»", $value);
		$pattern = "/&#8658;/";
		$value = preg_replace($pattern, "⇒", $value);
		$pattern = "/&#8594;/";
		$value = preg_replace($pattern, "→", $value);
		$pattern = "/&#8969;/";
		$value = preg_replace($pattern, "⌉", $value);
		$pattern = "/&#8221;/";
		$value = preg_replace($pattern, "”", $value);
		$pattern = "/&#8476;/";
		$value = preg_replace($pattern, "ℜ", $value);
		$pattern = "/&#174;/";
		$value = preg_replace($pattern, "®", $value);
		$pattern = "/&#8971;/";
		$value = preg_replace($pattern, "⌋", $value);
		$pattern = "/&#929;/";
		$value = preg_replace($pattern, "Ρ", $value);
		$pattern = "/&#961;/";
		$value = preg_replace($pattern, "ρ", $value);
		$pattern = "/&#8250;/";
		$value = preg_replace($pattern, "›", $value);
		$pattern = "/&#8217;/";
		$value = preg_replace($pattern, "’", $value);
		$pattern = "/&#8218;/";
		$value = preg_replace($pattern, "‚", $value);
		$pattern = "/&#352;/";
		$value = preg_replace($pattern, "Š", $value);
		$pattern = "/&#353;/";
		$value = preg_replace($pattern, "š", $value);
		$pattern = "/&#8901;/";
		$value = preg_replace($pattern, "⋅", $value);
		$pattern = "/&#167;/";
		$value = preg_replace($pattern, "§", $value);
		$pattern = "/&#173;/";
		$value = preg_replace($pattern, "­", $value);
		$pattern = "/&#931;/";
		$value = preg_replace($pattern, "Σ", $value);
		$pattern = "/&#963;/";
		$value = preg_replace($pattern, "σ", $value);
		$pattern = "/&#962;/";
		$value = preg_replace($pattern, "ς", $value);
		$pattern = "/&#8764;/";
		$value = preg_replace($pattern, "∼", $value);
		$pattern = "/&#9824;/";
		$value = preg_replace($pattern, "♠", $value);
		$pattern = "/&#8834;/";
		$value = preg_replace($pattern, "⊂", $value);
		$pattern = "/&#8838;/";
		$value = preg_replace($pattern, "⊆", $value);
		$pattern = "/&#8721;/";
		$value = preg_replace($pattern, "∑", $value);
		$pattern = "/&#8835;/";
		$value = preg_replace($pattern, "⊃", $value);
		$pattern = "/&#185;/";
		$value = preg_replace($pattern, "¹", $value);
		$pattern = "/&#178;/";
		$value = preg_replace($pattern, "²", $value);
		$pattern = "/&#179;/";
		$value = preg_replace($pattern, "³", $value);
		$pattern = "/&#8839;/";
		$value = preg_replace($pattern, "⊇", $value);
		$pattern = "/&#223;/";
		$value = preg_replace($pattern, "ß", $value);
		$pattern = "/&#932;/";
		$value = preg_replace($pattern, "Τ", $value);
		$pattern = "/&#964;/";
		$value = preg_replace($pattern, "τ", $value);
		$pattern = "/&#8756;/";
		$value = preg_replace($pattern, "∴", $value);
		$pattern = "/&#920;/";
		$value = preg_replace($pattern, "Θ", $value);
		$pattern = "/&#952;/";
		$value = preg_replace($pattern, "θ", $value);
		$pattern = "/&#977;/";
		$value = preg_replace($pattern, "ϑ", $value);
		$pattern = "/&#222;/";
		$value = preg_replace($pattern, "Þ", $value);
		$pattern = "/&#254;/";
		$value = preg_replace($pattern, "þ", $value);
		$pattern = "/&#732;/";
		$value = preg_replace($pattern, "˜", $value);
		$pattern = "/&#215;/";
		$value = preg_replace($pattern, "×", $value);
		$pattern = "/&#8482;/";
		$value = preg_replace($pattern, "™", $value);
		$pattern = "/&#250;/";
		$value = preg_replace($pattern, "ú", $value);
		$pattern = "/&#218;/";
		$value = preg_replace($pattern, "Ú", $value);
		$pattern = "/&#8657;/";
		$value = preg_replace($pattern, "⇑", $value);
		$pattern = "/&#8593;/";
		$value = preg_replace($pattern, "↑", $value);
		$pattern = "/&#251;/";
		$value = preg_replace($pattern, "û", $value);
		$pattern = "/&#219;/";
		$value = preg_replace($pattern, "Û", $value);
		$pattern = "/&#217;/";
		$value = preg_replace($pattern, "Ù", $value);
		$pattern = "/&#249;/";
		$value = preg_replace($pattern, "ù", $value);
		$pattern = "/&#168;/";
		$value = preg_replace($pattern, "¨", $value);
		$pattern = "/&#978;/";
		$value = preg_replace($pattern, "ϒ", $value);
		$pattern = "/&#965;/";
		$value = preg_replace($pattern, "υ", $value);
		$pattern = "/&#933;/";
		$value = preg_replace($pattern, "Υ", $value);
		$pattern = "/&#252;/";
		$value = preg_replace($pattern, "ü", $value);
		$pattern = "/&#220;/";
		$value = preg_replace($pattern, "Ü", $value);
		$pattern = "/&#8472;/";
		$value = preg_replace($pattern, "℘", $value);
		$pattern = "/&#958;/";
		$value = preg_replace($pattern, "ξ", $value);
		$pattern = "/&#926;/";
		$value = preg_replace($pattern, "Ξ", $value);
		$pattern = "/&#253;/";
		$value = preg_replace($pattern, "ý", $value);
		$pattern = "/&#221;/";
		$value = preg_replace($pattern, "Ý", $value);
		$pattern = "/&#165;/";
		$value = preg_replace($pattern, "¥", $value);
		$pattern = "/&#255;/";
		$value = preg_replace($pattern, "ÿ", $value);
		$pattern = "/&#376;/";
		$value = preg_replace($pattern, "Ÿ", $value);
		$pattern = "/&#918;/";
		$value = preg_replace($pattern, "Ζ", $value);
		$pattern = "/&#950;/";
		$value = preg_replace($pattern, "ζ", $value);
		
		// unclean ...
		$pattern = "/\.\.\./";
		$value = preg_replace($pattern, "...", $value);		   	
		
		// Remove extra white spaces
		$pattern = "/&#8195;&#8195;/";
		$value = preg_replace($pattern, "  ", $value);
		$pattern = "/&#8195;\ /";
		$value = preg_replace($pattern, "  ", $value);
		$pattern = "/&#8195;/";
		$value = preg_replace($pattern, " ", $value);
		$pattern = "/\ &nbsp;/";
		$value = preg_replace($pattern, "  ", $value);
		$pattern = "/&nbsp;\ /";
		$value = preg_replace($pattern, "  ", $value);
		$pattern = "/\ &#8195;/";
		$value = preg_replace($pattern, "  ", $value);
		$pattern = "/\  /";
		$value = preg_replace($pattern, "  ", $value);
		
		// trademark, copyright, ...
		$pattern = "/&trade;/";    
		$value = preg_replace($pattern, "(tm)", $value);
		$pattern = "/&copy;/";    
		$value = preg_replace($pattern, "(c)", $value);
		$pattern = "/&reg;/";    
		$value = preg_replace($pattern, "(r)", $value);
		
		// apo$valueof
		$pattern = "/&#39;/";
		$value = preg_replace($pattern, "'", $value);

		return $value;
	}

	/**
	 * Char
	 *
	 * @param string $value
	 */
	public static function char($value)
	{
		// OMZETTEN VAN SPECIALE KARAKTERS NAAR TEKST
		/*$pattern = "/\&/";
		$value = preg_replace($pattern, "&#38", $value);*/
		
		$pattern = "/\Á/";
		$value = preg_replace($pattern, "&#193;", $value);
		$pattern = "/\á/";
		$value = preg_replace($pattern, "&#225;", $value);
		$pattern = "/\â/";
		$value = preg_replace($pattern, "&#226;", $value);
		$pattern = "/\Â/";
		$value = preg_replace($pattern, "&#194;", $value);
		$pattern = "/\´/";
		$value = preg_replace($pattern, "&#180;", $value);
		$pattern = "/\æ/";
		$value = preg_replace($pattern, "&#230;", $value);
		$pattern = "/\Æ/";
		$value = preg_replace($pattern, "&#198;", $value);
		$pattern = "/\À/";
		$value = preg_replace($pattern, "&#192;", $value);
		$pattern = "/\à/";
		$value = preg_replace($pattern, "&#224;", $value);
		$pattern = "/\Α/";
		$value = preg_replace($pattern, "&#913;", $value);
		$pattern = "/\α/";
		$value = preg_replace($pattern, "&#945;", $value);
		$pattern = "/\å/";
		$value = preg_replace($pattern, "&#229;", $value);
		$pattern = "/\Å/";
		$value = preg_replace($pattern, "&#197;", $value);
		$pattern = "/\≈/";
		$value = preg_replace($pattern, "&#8776;", $value);
		$pattern = "/\Ã/";
		$value = preg_replace($pattern, "&#195;", $value);
		$pattern = "/\ã/";
		$value = preg_replace($pattern, "&#227;", $value);
		$pattern = "/\Ä/";
		$value = preg_replace($pattern, "&#196;", $value);
		$pattern = "/\ä/";
		$value = preg_replace($pattern, "&#228;", $value);
		$pattern = "/\„/";
		$value = preg_replace($pattern, "&#8222;", $value);
		$pattern = "/\Β/";
		$value = preg_replace($pattern, "&#914;", $value);
		$pattern = "/\β/";
		$value = preg_replace($pattern, "&#946;", $value);
		$pattern = "/\¦/";
		$value = preg_replace($pattern, "&#166;", $value);
		$pattern = "/\•/";
		$value = preg_replace($pattern, "&#8226;", $value);
		$pattern = "/\∩/";
		$value = preg_replace($pattern, "&#8745;", $value);
		$pattern = "/\Ç/";
		$value = preg_replace($pattern, "&#199;", $value);
		$pattern = "/\ç/";
		$value = preg_replace($pattern, "&#231;", $value);
		$pattern = "/\¸/";
		$value = preg_replace($pattern, "&#184;", $value);
		$pattern = "/\¢/";
		$value = preg_replace($pattern, "&#162;", $value);
		$pattern = "/\χ/";
		$value = preg_replace($pattern, "&#967;", $value);
		$pattern = "/\Χ/";
		$value = preg_replace($pattern, "&#935;", $value);
		$pattern = "/\ˆ/";
		$value = preg_replace($pattern, "&#710;", $value);
		$pattern = "/\♣/";
		$value = preg_replace($pattern, "&#9827;", $value);
		$pattern = "/\≅/";
		$value = preg_replace($pattern, "&#8773;", $value);
		$pattern = "/\©/";
		$value = preg_replace($pattern, "&#169;", $value);
		$pattern = "/\↵/";
		$value = preg_replace($pattern, "&#8629;", $value);
		$pattern = "/\∪/";
		$value = preg_replace($pattern, "&#8746;", $value);
		$pattern = "/\¤/";
		$value = preg_replace($pattern, "&#164;", $value);
		$pattern = "/\†/";
		$value = preg_replace($pattern, "&#8224;", $value);
		$pattern = "/\‡/";
		$value = preg_replace($pattern, "&#8225;", $value);
		$pattern = "/\⇓/";
		$value = preg_replace($pattern, "&#8659;", $value);
		$pattern = "/\↓/";
		$value = preg_replace($pattern, "&#8595;", $value);
		$pattern = "/\°/";
		$value = preg_replace($pattern, "&#176;", $value);
		$pattern = "/\Δ/";
		$value = preg_replace($pattern, "&#916;", $value);
		$pattern = "/\δ/";
		$value = preg_replace($pattern, "&#948;", $value);
		$pattern = "/\♦/";
		$value = preg_replace($pattern, "&#9830;", $value);
		$pattern = "/\÷/";
		$value = preg_replace($pattern, "&#247;", $value);
		$pattern = "/\é/";
		$value = preg_replace($pattern, "&#233;", $value);
		$pattern = "/\É/";
		$value = preg_replace($pattern, "&#201;", $value);
		$pattern = "/\Ê/";
		$value = preg_replace($pattern, "&#202;", $value);
		$pattern = "/\ê/";
		$value = preg_replace($pattern, "&#234;", $value);
		$pattern = "/\è/";
		$value = preg_replace($pattern, "&#232;", $value);
		$pattern = "/\È/";
		$value = preg_replace($pattern, "&#200;", $value);
		$pattern = "/\∅/";
		$value = preg_replace($pattern, "&#8709;", $value);
		$pattern = "/\ε/";
		$value = preg_replace($pattern, "&#949;", $value);
		$pattern = "/\Ε/";
		$value = preg_replace($pattern, "&#917;", $value);
		$pattern = "/\≡/";
		$value = preg_replace($pattern, "&#8801;", $value);
		$pattern = "/\Η/";
		$value = preg_replace($pattern, "&#919;", $value);
		$pattern = "/\η/";
		$value = preg_replace($pattern, "&#951;", $value);
		$pattern = "/\ð/";
		$value = preg_replace($pattern, "&#240;", $value);
		$pattern = "/\Ð/";
		$value = preg_replace($pattern, "&#208;", $value);
		$pattern = "/\ë/";
		$value = preg_replace($pattern, "&#235;", $value);
		$pattern = "/\Ë/";
		$value = preg_replace($pattern, "&#203;", $value);
		$pattern = "/\€/";
		$value = preg_replace($pattern, "&#8364;", $value);
		$pattern = "/\∃/";
		$value = preg_replace($pattern, "&#8707;", $value);
		$pattern = "/\ƒ/";
		$value = preg_replace($pattern, "&#402;", $value);
		$pattern = "/\∀/";
		$value = preg_replace($pattern, "&#8704;", $value);
		$pattern = "/\½/";
		$value = preg_replace($pattern, "&#189;", $value);
		$pattern = "/\¼/";
		$value = preg_replace($pattern, "&#188;", $value);
		$pattern = "/\¾/";
		$value = preg_replace($pattern, "&#190;", $value);
		$pattern = "/\⁄/";
		$value = preg_replace($pattern, "&#8260;", $value);
		$pattern = "/\Γ/";
		$value = preg_replace($pattern, "&#915;", $value);
		$pattern = "/\γ/";
		$value = preg_replace($pattern, "&#947;", $value);
		$pattern = "/\≥/";
		$value = preg_replace($pattern, "&#8805;", $value);
		//$pattern = "/\>/";
		//$value = preg_replace($pattern, "&#62;", $value);
		$pattern = "/\⇔/";
		$value = preg_replace($pattern, "&#8660;", $value);
		$pattern = "/\↔/";
		$value = preg_replace($pattern, "&#8596;", $value);
		$pattern = "/\♥/";
		$value = preg_replace($pattern, "&#9829;", $value);
		$pattern = "/\…/";
		$value = preg_replace($pattern, "&#8230;", $value);
		$pattern = "/\í/";
		$value = preg_replace($pattern, "&#237;", $value);
		$pattern = "/\Í/";
		$value = preg_replace($pattern, "&#205;", $value);
		$pattern = "/\î/";
		$value = preg_replace($pattern, "&#238;", $value);
		$pattern = "/\Î/";
		$value = preg_replace($pattern, "&#206;", $value);
		$pattern = "/\¡/";
		$value = preg_replace($pattern, "&#161;", $value);
		$pattern = "/\Ì/";
		$value = preg_replace($pattern, "&#204;", $value);
		$pattern = "/\ì/";
		$value = preg_replace($pattern, "&#236;", $value);
		$pattern = "/\∞/";
		$value = preg_replace($pattern, "&#8734;", $value);
		$pattern = "/\∫/";
		$value = preg_replace($pattern, "&#8747;", $value);
		$pattern = "/\Ι/";
		$value = preg_replace($pattern, "&#921;", $value);
		$pattern = "/\ι/";
		$value = preg_replace($pattern, "&#953;", $value);
		$pattern = "/\¿/";
		$value = preg_replace($pattern, "&#191;", $value);
		$pattern = "/\∈/";
		$value = preg_replace($pattern, "&#8712;", $value);
		$pattern = "/\Ï/";
		$value = preg_replace($pattern, "&#207;", $value);
		$pattern = "/\ï/";
		$value = preg_replace($pattern, "&#239;", $value);
		$pattern = "/\Κ/";
		$value = preg_replace($pattern, "&#922;", $value);
		$pattern = "/\κ/";
		$value = preg_replace($pattern, "&#954;", $value);
		$pattern = "/\λ/";
		$value = preg_replace($pattern, "&#955;", $value);
		$pattern = "/\Λ/";
		$value = preg_replace($pattern, "&#923;", $value);
		$pattern = "/\〈/";
		$value = preg_replace($pattern, "&#9001;", $value);
		$pattern = "/\«/";
		$value = preg_replace($pattern, "&#171;", $value);
		$pattern = "/\←/";
		$value = preg_replace($pattern, "&#8592;", $value);
		$pattern = "/\⇐/";
		$value = preg_replace($pattern, "&#8656;", $value);
		$pattern = "/\⌈/";
		$value = preg_replace($pattern, "&#8968;", $value);
		$pattern = "/\“/";
		$value = preg_replace($pattern, "&#8220;", $value);
		$pattern = "/\≤/";
		$value = preg_replace($pattern, "&#8804;", $value);
		$pattern = "/\⌊/";
		$value = preg_replace($pattern, "&#8970;", $value);
		$pattern = "/\∗/";
		$value = preg_replace($pattern, "&#8727;", $value);
		$pattern = "/\◊/";
		$value = preg_replace($pattern, "&#8974;", $value);
		$pattern = "/\‹/";
		$value = preg_replace($pattern, "&#8249;", $value);
		$pattern = "/\‘/";
		$value = preg_replace($pattern, "&#8216;", $value);
		//$pattern = "/\</";
		//$value = preg_replace($pattern, "&#60;", $value);
		$pattern = "/\¯/";
		$value = preg_replace($pattern, "&#175;", $value);
		$pattern = "/\—/";
		$value = preg_replace($pattern, "&#8212;", $value);
		$pattern = "/\µ/";
		$value = preg_replace($pattern, "&#181;", $value);
		$pattern = "/\·/";
		$value = preg_replace($pattern, "&#183;", $value);
		$pattern = "/\−/";
		$value = preg_replace($pattern, "&#8722;", $value);
		$pattern = "/\Μ/";
		$value = preg_replace($pattern, "&#924;", $value);
		$pattern = "/\μ/";
		$value = preg_replace($pattern, "&#956;", $value);
		$pattern = "/\∇/";
		$value = preg_replace($pattern, "&#8711;", $value);
		$pattern = "/\–/";
		$value = preg_replace($pattern, "&#8211;", $value);
		$pattern = "/\≠/";
		$value = preg_replace($pattern, "&#8800;", $value);
		$pattern = "/\∋/";
		$value = preg_replace($pattern, "&#8715;", $value);
		$pattern = "/\¬/";
		$value = preg_replace($pattern, "&#172;", $value);
		$pattern = "/\∉/";
		$value = preg_replace($pattern, "&#8713;", $value);
		$pattern = "/\⊄/";
		$value = preg_replace($pattern, "&#8836;", $value);
		$pattern = "/\ñ/";
		$value = preg_replace($pattern, "&#241;", $value);
		$pattern = "/\Ñ/";
		$value = preg_replace($pattern, "&#209;", $value);
		$pattern = "/\Ν/";
		$value = preg_replace($pattern, "&#925;", $value);
		$pattern = "/\ν/";
		$value = preg_replace($pattern, "&#957;", $value);
		$pattern = "/\ó/";
		$value = preg_replace($pattern, "&#243;", $value);
		$pattern = "/\Ó/";
		$value = preg_replace($pattern, "&#211;", $value);
		$pattern = "/\Ô/";
		$value = preg_replace($pattern, "&#212;", $value);
		$pattern = "/\ô/";
		$value = preg_replace($pattern, "&#244;", $value);
		$pattern = "/\Œ/";
		$value = preg_replace($pattern, "&#338;", $value);
		$pattern = "/\œ/";
		$value = preg_replace($pattern, "&#339;", $value);
		$pattern = "/\ò/";
		$value = preg_replace($pattern, "&#242;", $value);
		$pattern = "/\Ò/";
		$value = preg_replace($pattern, "&#210;", $value);
		$pattern = "/\‾/";
		$value = preg_replace($pattern, "&#8254;", $value);
		$pattern = "/\ω/";
		$value = preg_replace($pattern, "&#969;", $value);
		$pattern = "/\Ω/";
		$value = preg_replace($pattern, "&#937;", $value);
		$pattern = "/\Ο/";
		$value = preg_replace($pattern, "&#927;", $value);
		$pattern = "/\ο/";
		$value = preg_replace($pattern, "&#959;", $value);
		$pattern = "/\⊕/";
		$value = preg_replace($pattern, "&#8853;", $value);
		$pattern = "/\∨/";
		$value = preg_replace($pattern, "&#8744;", $value);
		$pattern = "/\ª/";
		$value = preg_replace($pattern, "&#170;", $value);
		$pattern = "/\º/";
		$value = preg_replace($pattern, "&#186;", $value);
		$pattern = "/\Ø/";
		$value = preg_replace($pattern, "&#216;", $value);
		$pattern = "/\ø/";
		$value = preg_replace($pattern, "&#248;", $value);
		$pattern = "/\Õ/";
		$value = preg_replace($pattern, "&#213;", $value);
		$pattern = "/\õ/";
		$value = preg_replace($pattern, "&#245;", $value);
		$pattern = "/\⊗/";
		$value = preg_replace($pattern, "&#8855;", $value);
		$pattern = "/\Ö/";
		$value = preg_replace($pattern, "&#214;", $value);
		$pattern = "/\ö/";
		$value = preg_replace($pattern, "&#246;", $value);
		$pattern = "/\¶/";
		$value = preg_replace($pattern, "&#182;", $value);
		$pattern = "/\∂/";
		$value = preg_replace($pattern, "&#8706;", $value);
		$pattern = "/\‰/";
		$value = preg_replace($pattern, "&#8240;", $value);
		$pattern = "/\⊥/";
		$value = preg_replace($pattern, "&#8869;", $value);
		$pattern = "/\φ/";
		$value = preg_replace($pattern, "&#966;", $value);
		$pattern = "/\Φ/";
		$value = preg_replace($pattern, "&#934;", $value);
		$pattern = "/\Π/";
		$value = preg_replace($pattern, "&#928;", $value);
		$pattern = "/\π/";
		$value = preg_replace($pattern, "&#960;", $value);
		$pattern = "/\ϖ/";
		$value = preg_replace($pattern, "&#982;", $value);
		$pattern = "/\±/";
		$value = preg_replace($pattern, "&#177;", $value);
		$pattern = "/\£/";
		$value = preg_replace($pattern, "&#163;", $value);
		$pattern = "/\″/";
		$value = preg_replace($pattern, "&#8243;", $value);
		$pattern = "/\′/";
		$value = preg_replace($pattern, "&#8242;", $value);
		$pattern = "/\∏/";
		$value = preg_replace($pattern, "&#8719;", $value);
		$pattern = "/\∝/";
		$value = preg_replace($pattern, "&#8733;", $value);
		$pattern = "/\ψ/";
		$value = preg_replace($pattern, "&#968;", $value);
		$pattern = "/\Ψ/";
		$value = preg_replace($pattern, "&#936;", $value);
		//$pattern = "/\'/";
		//$value = preg_replace($pattern, "&#34;", $value);
		$pattern = "/\√/";
		$value = preg_replace($pattern, "&#8730;", $value);
		$pattern = "/\〉/";
		$value = preg_replace($pattern, "&#9002;", $value);
		$pattern = "/\»/";
		$value = preg_replace($pattern, "&#187;", $value);
		$pattern = "/\⇒/";
		$value = preg_replace($pattern, "&#8658;", $value);
		$pattern = "/\→/";
		$value = preg_replace($pattern, "&#8594;", $value);
		$pattern = "/\⌉/";
		$value = preg_replace($pattern, "&#8969;", $value);
		$pattern = "/\”/";
		$value = preg_replace($pattern, "&#8221;", $value);
		$pattern = "/\ℜ/";
		$value = preg_replace($pattern, "&#8476;", $value);
		$pattern = "/\®/";
		$value = preg_replace($pattern, "&#174;", $value);
		$pattern = "/\⌋/";
		$value = preg_replace($pattern, "&#8971;", $value);
		$pattern = "/\Ρ/";
		$value = preg_replace($pattern, "&#929;", $value);
		$pattern = "/\ρ/";
		$value = preg_replace($pattern, "&#961;", $value);
		$pattern = "/\›/";
		$value = preg_replace($pattern, "&#8250;", $value);
		$pattern = "/\’/";
		$value = preg_replace($pattern, "&#8217;", $value);
		$pattern = "/\‚/";
		$value = preg_replace($pattern, "&#8218;", $value);
		$pattern = "/\Š/";
		$value = preg_replace($pattern, "&#352;", $value);
		$pattern = "/\š/";
		$value = preg_replace($pattern, "&#353;", $value);
		$pattern = "/\⋅/";
		$value = preg_replace($pattern, "&#8901;", $value);
		$pattern = "/\§/";
		$value = preg_replace($pattern, "&#167;", $value);
		$pattern = "/\­/";
		$value = preg_replace($pattern, "&#173;", $value);
		$pattern = "/\Σ/";
		$value = preg_replace($pattern, "&#931;", $value);
		$pattern = "/\σ/";
		$value = preg_replace($pattern, "&#963;", $value);
		$pattern = "/\ς/";
		$value = preg_replace($pattern, "&#962;", $value);
		$pattern = "/\∼/";
		$value = preg_replace($pattern, "&#8764;", $value);
		$pattern = "/\♠/";
		$value = preg_replace($pattern, "&#9824;", $value);
		$pattern = "/\⊂/";
		$value = preg_replace($pattern, "&#8834;", $value);
		$pattern = "/\⊆/";
		$value = preg_replace($pattern, "&#8838;", $value);
		$pattern = "/\∑/";
		$value = preg_replace($pattern, "&#8721;", $value);
		$pattern = "/\⊃/";
		$value = preg_replace($pattern, "&#8835;", $value);
		$pattern = "/\¹/";
		$value = preg_replace($pattern, "&#185;", $value);
		$pattern = "/\²/";
		$value = preg_replace($pattern, "&#178;", $value);
		$pattern = "/\³/";
		$value = preg_replace($pattern, "&#179;", $value);
		$pattern = "/\⊇/";
		$value = preg_replace($pattern, "&#8839;", $value);
		$pattern = "/\ß/";
		$value = preg_replace($pattern, "&#223;", $value);
		$pattern = "/\Τ/";
		$value = preg_replace($pattern, "&#932;", $value);
		$pattern = "/\τ/";
		$value = preg_replace($pattern, "&#964;", $value);
		$pattern = "/\∴/";
		$value = preg_replace($pattern, "&#8756;", $value);
		$pattern = "/\Θ/";
		$value = preg_replace($pattern, "&#920;", $value);
		$pattern = "/\θ/";
		$value = preg_replace($pattern, "&#952;", $value);
		$pattern = "/\ϑ/";
		$value = preg_replace($pattern, "&#977;", $value);
		$pattern = "/\Þ/";
		$value = preg_replace($pattern, "&#222;", $value);
		$pattern = "/\þ/";
		$value = preg_replace($pattern, "&#254;", $value);
		$pattern = "/\˜/";
		$value = preg_replace($pattern, "&#732;", $value);
		$pattern = "/\×/";
		$value = preg_replace($pattern, "&#215;", $value);
		$pattern = "/\™/";
		$value = preg_replace($pattern, "&#8482;", $value);
		$pattern = "/\ú/";
		$value = preg_replace($pattern, "&#250;", $value);
		$pattern = "/\Ú/";
		$value = preg_replace($pattern, "&#218;", $value);
		$pattern = "/\⇑/";
		$value = preg_replace($pattern, "&#8657;", $value);
		$pattern = "/\↑/";
		$value = preg_replace($pattern, "&#8593;", $value);
		$pattern = "/\û/";
		$value = preg_replace($pattern, "&#251;", $value);
		$pattern = "/\Û/";
		$value = preg_replace($pattern, "&#219;", $value);
		$pattern = "/\Ù/";
		$value = preg_replace($pattern, "&#217;", $value);
		$pattern = "/\ù/";
		$value = preg_replace($pattern, "&#249;", $value);
		$pattern = "/\¨/";
		$value = preg_replace($pattern, "&#168;", $value);
		$pattern = "/\ϒ/";
		$value = preg_replace($pattern, "&#978;", $value);
		$pattern = "/\υ/";
		$value = preg_replace($pattern, "&#965;", $value);
		$pattern = "/\Υ/";
		$value = preg_replace($pattern, "&#933;", $value);
		$pattern = "/\ü/";
		$value = preg_replace($pattern, "&#252;", $value);
		$pattern = "/\Ü/";
		$value = preg_replace($pattern, "&#220;", $value);
		$pattern = "/\℘/";
		$value = preg_replace($pattern, "&#8472;", $value);
		$pattern = "/\ξ/";
		$value = preg_replace($pattern, "&#958;", $value);
		$pattern = "/\Ξ/";
		$value = preg_replace($pattern, "&#926;", $value);
		$pattern = "/\ý/";
		$value = preg_replace($pattern, "&#253;", $value);
		$pattern = "/\Ý/";
		$value = preg_replace($pattern, "&#221;", $value);
		$pattern = "/\¥/";
		$value = preg_replace($pattern, "&#165;", $value);
		$pattern = "/\ÿ/";
		$value = preg_replace($pattern, "&#255;", $value);
		$pattern = "/\Ÿ/";
		$value = preg_replace($pattern, "&#376;", $value);
		$pattern = "/\Ζ/";
		$value = preg_replace($pattern, "&#918;", $value);
		$pattern = "/\ζ/";
		$value = preg_replace($pattern, "&#950;", $value);

		// 3 points
		$pattern = "/\.\.\./";
		$value = preg_replace($pattern, "...", $value);

		// turn spaces to htmlText
		$pattern = "/\ {2}/";
		$value = preg_replace($pattern, "&#8195;&#8195;", $value);

		// trademark, copyright, ...
		$pattern = "/\(\t\m\)/";    
		$value = preg_replace($pattern, "&trade;", $value);

		// the rule below had a fault according to AMFPHP
		/*$pattern = "/\(\c\)/";    
		$value = preg_replace($pattern, "&copy", $value);*/
		$pattern = "/\(\r\)/";    
		$value = preg_replace($pattern, "&reg;", $value);

		// apo$valueof
		$pattern = "/\'/";
		$value = preg_replace($pattern, "&#39;", $value);

		return $value;
	}
	
	/*
	function unDecode($value){
	
		$pattern = "/&#193;/";
		$value = preg_replace($pattern, "", $value);	// Á
		$pattern = "/&#225;/";
		$value = preg_replace($pattern, "", $value);	// á
		$pattern = "/&#226;/";
		$value = preg_replace($pattern, "", $value);	// â
		$pattern = "/&#194;/";
		$value = preg_replace($pattern, "", $value);	// Â
		$pattern = "/&#180;/";
		$value = preg_replace($pattern, "", $value);	// ´
		$pattern = "/&#230;/";
		$value = preg_replace($pattern, "", $value);	// æ
		$pattern = "/&#198;/";
		$value = preg_replace($pattern, "", $value);	// Æ
		$pattern = "/&#192;/";
		$value = preg_replace($pattern, "", $value);	// À
		$pattern = "/&#224;/";
		$value = preg_replace($pattern, "", $value);	// à
		$pattern = "/&#913;/";
		$value = preg_replace($pattern, "", $value);	// Α
		$pattern = "/&#945;/";
		$value = preg_replace($pattern, "", $value);	// α
		/*$pattern = "/&#38;/";
		$value = preg_replace($pattern, "&", $value);*/
		/*
		$pattern = "/&#229;/";
		$value = preg_replace($pattern, "", $value);	// å
		$pattern = "/&#197;/";
		$value = preg_replace($pattern, "", $value);	// Å
		$pattern = "/&#8776;/";
		$value = preg_replace($pattern, "", $value);	// ≈
		$pattern = "/&#195;/";
		$value = preg_replace($pattern, "", $value);	// Ã 
		$pattern = "/&#227;/";
		$value = preg_replace($pattern, "", $value);	// ã
		$pattern = "/&#196;/";
		$value = preg_replace($pattern, "", $value);	// Ä
		$pattern = "/&#228;/";
		$value = preg_replace($pattern, "", $value);	// ä
		$pattern = "/&#8222;/";
		$value = preg_replace($pattern, "", $value);	// „
		$pattern = "/&#914;/";
		$value = preg_replace($pattern, "", $value);	//Β 
		$pattern = "/&#946;/";
		$value = preg_replace($pattern, "", $value);	// β
		$pattern = "/&#166;/";
		$value = preg_replace($pattern, "", $value);	// ¦
		$pattern = "/&#8226;/";
		$value = preg_replace($pattern, "", $value);	// •
		$pattern = "/&#8745;/";
		$value = preg_replace($pattern, "", $value);	// ∩
		$pattern = "/&#199;/";
		$value = preg_replace($pattern, "", $value);	// Ç
		$pattern = "/&#231;/";
		$value = preg_replace($pattern, "", $value);	// ç
		$pattern = "/&#184;/";
		$value = preg_replace($pattern, "", $value);	// ¸
		$pattern = "/&#162;/";
		$value = preg_replace($pattern, "", $value);	// ¢
		$pattern = "/&#967;/";
		$value = preg_replace($pattern, "", $value);	// χ
		$pattern = "/&#935;/";
		$value = preg_replace($pattern, "", $value);	// Χ
		$pattern = "/&#710;/";
		$value = preg_replace($pattern, "", $value);	// ˆ
		$pattern = "/&#9827;/";
		$value = preg_replace($pattern, "", $value);	// ♣
		$pattern = "/&#8773;/";
		$value = preg_replace($pattern, "", $value);	// ≅
		$pattern = "/&#169;/";
		$value = preg_replace($pattern, "", $value);	// ©
		$pattern = "/&#8629;/";
		$value = preg_replace($pattern, "", $value);	// ↵
		$pattern = "/&#8746;/";
		$value = preg_replace($pattern, "", $value);	// ∪
		$pattern = "/&#164;/";
		$value = preg_replace($pattern, "", $value);	// ¤
		$pattern = "/&#8224;/";
		$value = preg_replace($pattern, "", $value);	// †
		$pattern = "/&#8225;/";
		$value = preg_replace($pattern, "", $value);	// ‡
		$pattern = "/&#8659;/";
		$value = preg_replace($pattern, "", $value);	// ⇓
		$pattern = "/&#8595;/";
		$value = preg_replace($pattern, "", $value);	// ↓
		$pattern = "/&#176;/";
		$value = preg_replace($pattern, "", $value);	// °
		$pattern = "/&#916;/";
		$value = preg_replace($pattern, "", $value);	// Δ
		$pattern = "/&#948;/";
		$value = preg_replace($pattern, "", $value);	// δ
		$pattern = "/&#9830;/";
		$value = preg_replace($pattern, "", $value);	// ♦
		$pattern = "/&#247;/";
		$value = preg_replace($pattern, "", $value);	// ÷
		$pattern = "/&#233;/";
		$value = preg_replace($pattern, "", $value);	// é
		$pattern = "/&#201;/";
		$value = preg_replace($pattern, "", $value);	// É
		$pattern = "/&#202;/";
		$value = preg_replace($pattern, "Ê", $value);	// 
		$pattern = "/&#234;/";
		$value = preg_replace($pattern, "ê", $value);	// 
		$pattern = "/&#232;/";
		$value = preg_replace($pattern, "è", $value);	// 
		$pattern = "/&#200;/";
		$value = preg_replace($pattern, "È", $value);	// 
		$pattern = "/&#8709;/";
		$value = preg_replace($pattern, "∅", $value);	// 
		$pattern = "/&#949;/";
		$value = preg_replace($pattern, "ε", $value);	// 
		$pattern = "/&#917;/";
		$value = preg_replace($pattern, "Ε", $value);	// 
		$pattern = "/&#8801;/";
		$value = preg_replace($pattern, "≡", $value);	// 
		$pattern = "/&#919;/";
		$value = preg_replace($pattern, "Η", $value);	// 
		$pattern = "/&#951;/";
		$value = preg_replace($pattern, "η", $value);	// 
		$pattern = "/&#240;/";
		$value = preg_replace($pattern, "ð", $value);	// 
		$pattern = "/&#208;/";
		$value = preg_replace($pattern, "Ð", $value);	// 
		$pattern = "/&#235;/";
		$value = preg_replace($pattern, "ë", $value);	// 
		$pattern = "/&#203;/";
		$value = preg_replace($pattern, "Ë", $value);	// 
		$pattern = "/&#8364;/";
		$value = preg_replace($pattern, "€", $value);	// 
		$pattern = "/&#8707;/";
		$value = preg_replace($pattern, "∃", $value);	// 
		$pattern = "/&#402;/";
		$value = preg_replace($pattern, "ƒ", $value);	// 
		$pattern = "/&#8704;/";
		$value = preg_replace($pattern, "∀", $value);	// 
		$pattern = "/&#189;/";
		$value = preg_replace($pattern, "½", $value);	// 
		$pattern = "/&#188;/";
		$value = preg_replace($pattern, "¼", $value);	// 
		$pattern = "/&#190;/";
		$value = preg_replace($pattern, "¾", $value);	// 
		$pattern = "/&#8260;/";
		$value = preg_replace($pattern, "⁄", $value);	// 
		$pattern = "/&#915;/";
		$value = preg_replace($pattern, "Γ", $value);	// 
		$pattern = "/&#947;/";
		$value = preg_replace($pattern, "γ", $value);	// 
		$pattern = "/&#8805;/";
		$value = preg_replace($pattern, "≥", $value);	// 
		$pattern = "/&#62;/";
		$value = preg_replace($pattern, ">", $value);	// 
		$pattern = "/&#8660;/";
		$value = preg_replace($pattern, "⇔", $value);	// 
		$pattern = "/&#8596;/";
		$value = preg_replace($pattern, "↔", $value);	// 
		$pattern = "/&#9829;/";
		$value = preg_replace($pattern, "♥", $value);	// 
		$pattern = "/&#8230;/";
		$value = preg_replace($pattern, "…", $value);	// 
		$pattern = "/&#237;/";
		$value = preg_replace($pattern, "í", $value);	// 
		$pattern = "/&#205;/";
		$value = preg_replace($pattern, "Í", $value);	// 
		$pattern = "/&#238;/";
		$value = preg_replace($pattern, "î", $value);	// 
		$pattern = "/&#206;/";
		$value = preg_replace($pattern, "Î", $value);	// 
		$pattern = "/&#161;/";
		$value = preg_replace($pattern, "¡", $value);	// 
		$pattern = "/&#204;/";
		$value = preg_replace($pattern, "Ì", $value);	// 
		$pattern = "/&#236;/";
		$value = preg_replace($pattern, "ì", $value);	// 
		$pattern = "/&#8734;/";
		$value = preg_replace($pattern, "∞", $value);	// 
		$pattern = "/&#8747;/";
		$value = preg_replace($pattern, "∫", $value);	// 
		$pattern = "/&#921;/";
		$value = preg_replace($pattern, "Ι", $value);	// 
		$pattern = "/&#953;/";
		$value = preg_replace($pattern, "ι", $value);	// 
		$pattern = "/&#191;/";
		$value = preg_replace($pattern, "¿", $value);	// 
		$pattern = "/&#8712;/";
		$value = preg_replace($pattern, "∈", $value);	// 
		$pattern = "/&#207;/";
		$value = preg_replace($pattern, "Ï", $value);	// 
		$pattern = "/&#239;/";
		$value = preg_replace($pattern, "ï", $value);	// 
		$pattern = "/&#922;/";
		$value = preg_replace($pattern, "Κ", $value);	// 
		$pattern = "/&#954;/";
		$value = preg_replace($pattern, "κ", $value);	// 
		$pattern = "/&#955;/";
		$value = preg_replace($pattern, "λ", $value);	// 
		$pattern = "/&#923;/";
		$value = preg_replace($pattern, "Λ", $value);	// 
		$pattern = "/&#9001;/";
		$value = preg_replace($pattern, "〈", $value);	// 
		$pattern = "/&#171;/";
		$value = preg_replace($pattern, "«", $value);	// 
		$pattern = "/&#8592;/";
		$value = preg_replace($pattern, "←", $value);	// 
		$pattern = "/&#8656;/";
		$value = preg_replace($pattern, "⇐", $value);	// 
		$pattern = "/&#8968;/";
		$value = preg_replace($pattern, "⌈", $value);	// 
		$pattern = "/&#8220;/";
		$value = preg_replace($pattern, "“", $value);	// 
		$pattern = "/&#8804;/";
		$value = preg_replace($pattern, "≤", $value);	// 
		$pattern = "/&#8970;/";
		$value = preg_replace($pattern, "⌊", $value);	// 
		$pattern = "/&#8727;/";
		$value = preg_replace($pattern, "∗", $value);	// 
		$pattern = "/&#8974;/";
		$value = preg_replace($pattern, "◊", $value);	// 
		$pattern = "/&#8249;/";
		$value = preg_replace($pattern, "‹", $value);	// 
		$pattern = "/&#8216;/";
		$value = preg_replace($pattern, "‘", $value);	// 
		$pattern = "/&#60;/";
		$value = preg_replace($pattern, "<", $value);	// 
		$pattern = "/&#175;/";
		$value = preg_replace($pattern, "¯", $value);	// 
		$pattern = "/&#8212;/";
		$value = preg_replace($pattern, "—", $value);	// 
		$pattern = "/&#181;/";
		$value = preg_replace($pattern, "µ", $value);	// 
		$pattern = "/&#183;/";
		$value = preg_replace($pattern, "·", $value);	// 
		$pattern = "/&#8722;/";
		$value = preg_replace($pattern, "−", $value);	// 
		$pattern = "/&#924;/";
		$value = preg_replace($pattern, "Μ", $value);	// 
		$pattern = "/&#956;/";
		$value = preg_replace($pattern, "μ", $value);	// 
		$pattern = "/&#8711;/";
		$value = preg_replace($pattern, "∇", $value);	// 
		$pattern = "/&#8211;/";
		$value = preg_replace($pattern, "–", $value);	// 
		$pattern = "/&#8800;/";
		$value = preg_replace($pattern, "≠", $value);	// 
		$pattern = "/&#8715;/";
		$value = preg_replace($pattern, "∋", $value);	// 
		$pattern = "/&#172;/";
		$value = preg_replace($pattern, "¬", $value);	// 
		$pattern = "/&#8713;/";
		$value = preg_replace($pattern, "∉", $value);	// 
		$pattern = "/&#8836;/";
		$value = preg_replace($pattern, "⊄", $value);	// 
		$pattern = "/&#241;/";
		$value = preg_replace($pattern, "ñ", $value);	// 
		$pattern = "/&#209;/";
		$value = preg_replace($pattern, "Ñ", $value);	// 
		$pattern = "/&#925;/";
		$value = preg_replace($pattern, "Ν", $value);	// 
		$pattern = "/&#957;/";
		$value = preg_replace($pattern, "ν", $value);	// 
		$pattern = "/&#243;/";
		$value = preg_replace($pattern, "ó", $value);	// 
		$pattern = "/&#211;/";
		$value = preg_replace($pattern, "Ó", $value);	// 
		$pattern = "/&#212;/";
		$value = preg_replace($pattern, "Ô", $value);	// 
		$pattern = "/&#244;/";
		$value = preg_replace($pattern, "ô", $value);	// 
		$pattern = "/&#338;/";
		$value = preg_replace($pattern, "Œ", $value);	// 
		$pattern = "/&#339;/";
		$value = preg_replace($pattern, "œ", $value);	// 
		$pattern = "/&#242;/";
		$value = preg_replace($pattern, "ò", $value);	// 
		$pattern = "/&#210;/";
		$value = preg_replace($pattern, "Ò", $value);	// 
		$pattern = "/&#8254;/";
		$value = preg_replace($pattern, "‾", $value);	// 
		$pattern = "/&#969;/";
		$value = preg_replace($pattern, "ω", $value);	// 
		$pattern = "/&#937;/";
		$value = preg_replace($pattern, "Ω", $value);	// 
		$pattern = "/&#927;/";
		$value = preg_replace($pattern, "Ο", $value);	// 
		$pattern = "/&#959;/";
		$value = preg_replace($pattern, "ο", $value);	// 
		$pattern = "/&#8853;/";
		$value = preg_replace($pattern, "⊕", $value);	// 
		$pattern = "/&#8744;/";
		$value = preg_replace($pattern, "∨", $value);	// 
		$pattern = "/&#170;/";
		$value = preg_replace($pattern, "ª", $value);	// 
		$pattern = "/&#186;/";
		$value = preg_replace($pattern, "º", $value);	// 
		$pattern = "/&#216;/";
		$value = preg_replace($pattern, "Ø", $value);	// 
		$pattern = "/&#248;/";
		$value = preg_replace($pattern, "ø", $value);	// 
		$pattern = "/&#213;/";
		$value = preg_replace($pattern, "Õ", $value);	// 
		$pattern = "/&#245;/";
		$value = preg_replace($pattern, "õ", $value);	// 
		$pattern = "/&#8855;/";
		$value = preg_replace($pattern, "⊗", $value);	// 
		$pattern = "/&#214;/";
		$value = preg_replace($pattern, "Ö", $value);	// 
		$pattern = "/&#246;/";
		$value = preg_replace($pattern, "ö", $value);	// 
		$pattern = "/&#182;/";
		$value = preg_replace($pattern, "¶", $value);	// 
		$pattern = "/&#8706;/";
		$value = preg_replace($pattern, "∂", $value);	// 
		$pattern = "/&#8240;/";
		$value = preg_replace($pattern, "‰", $value);	// 
		$pattern = "/&#8869;/";
		$value = preg_replace($pattern, "⊥", $value);	// 
		$pattern = "/&#966;/";
		$value = preg_replace($pattern, "φ", $value);	// 
		$pattern = "/&#934;/";
		$value = preg_replace($pattern, "Φ", $value);	// 
		$pattern = "/&#928;/";
		$value = preg_replace($pattern, "Π", $value);	// 
		$pattern = "/&#960;/";
		$value = preg_replace($pattern, "π", $value);	// 
		$pattern = "/&#982;/";
		$value = preg_replace($pattern, "ϖ", $value);	// 
		$pattern = "/&#177;/";
		$value = preg_replace($pattern, "±", $value);	// 
		$pattern = "/&#163;/";
		$value = preg_replace($pattern, "£", $value);	// 
		$pattern = "/&#8243;/";
		$value = preg_replace($pattern, "″", $value);	// 
		$pattern = "/&#8242;/";
		$value = preg_replace($pattern, "′", $value);	// 
		$pattern = "/&#8719;/";
		$value = preg_replace($pattern, "∏", $value);	// 
		$pattern = "/&#8733;/";
		$value = preg_replace($pattern, "∝", $value);	// 
		$pattern = "/&#968;/";
		$value = preg_replace($pattern, "ψ", $value);	// 
		$pattern = "/&#936;/";
		$value = preg_replace($pattern, "Ψ", $value);	// 
		//$pattern = "/&#34;/g;//$value = preg_replace($pattern, """, $value);
		$pattern = "/&#8730;/";
		$value = preg_replace($pattern, "√", $value);	// 
		$pattern = "/&#9002;/";
		$value = preg_replace($pattern, "〉", $value);	// 
		$pattern = "/&#187;/";
		$value = preg_replace($pattern, "»", $value);	// 
		$pattern = "/&#8658;/";
		$value = preg_replace($pattern, "⇒", $value);	// 
		$pattern = "/&#8594;/";
		$value = preg_replace($pattern, "→", $value);	// 
		$pattern = "/&#8969;/";
		$value = preg_replace($pattern, "⌉", $value);	// 
		$pattern = "/&#8221;/";
		$value = preg_replace($pattern, "”", $value);	// 
		$pattern = "/&#8476;/";
		$value = preg_replace($pattern, "ℜ", $value);	// 
		$pattern = "/&#174;/";
		$value = preg_replace($pattern, "®", $value);	// 
		$pattern = "/&#8971;/";
		$value = preg_replace($pattern, "⌋", $value);	// 
		$pattern = "/&#929;/";
		$value = preg_replace($pattern, "Ρ", $value);	// 
		$pattern = "/&#961;/";
		$value = preg_replace($pattern, "ρ", $value);	// 
		$pattern = "/&#8250;/";
		$value = preg_replace($pattern, "›", $value);	// 
		$pattern = "/&#8217;/";
		$value = preg_replace($pattern, "’", $value);	// 
		$pattern = "/&#8218;/";
		$value = preg_replace($pattern, "‚", $value);	// 
		$pattern = "/&#352;/";
		$value = preg_replace($pattern, "Š", $value);	// 
		$pattern = "/&#353;/";
		$value = preg_replace($pattern, "š", $value);	// 
		$pattern = "/&#8901;/";
		$value = preg_replace($pattern, "⋅", $value);	// 
		$pattern = "/&#167;/";
		$value = preg_replace($pattern, "§", $value);	// 
		$pattern = "/&#173;/";
		$value = preg_replace($pattern, "­", $value);	// 
		$pattern = "/&#931;/";
		$value = preg_replace($pattern, "Σ", $value);	// 
		$pattern = "/&#963;/";
		$value = preg_replace($pattern, "σ", $value);	// 
		$pattern = "/&#962;/";
		$value = preg_replace($pattern, "ς", $value);	// 
		$pattern = "/&sim;/";
		$value = preg_replace($pattern, "&#8764;", $value);	// ∼	
		$pattern = "/&spades;/";
		$value = preg_replace($pattern, "&#9824;", $value);	// 	♠
		$pattern = "/&sub;/";
		$value = preg_replace($pattern, "&#8834;", $value);	// 	⊂
		$pattern = "/&sube;/";
		$value = preg_replace($pattern, "&#8838;", $value);	// 	⊆
		$pattern = "/&sum;/";
		$value = preg_replace($pattern, "&#8721;", $value);	// ∑	
		$pattern = "/&sup;/";
		$value = preg_replace($pattern, "&#8835;", $value);	// ⊃	
		$pattern = "/&sup1;/";
		$value = preg_replace($pattern, "&#185;", $value);	// 	¹
		$pattern = "/&sup2;/";
		$value = preg_replace($pattern, "&#178;", $value);	// ²	
		$pattern = "/&sup3;/";
		$value = preg_replace($pattern, "&#179;", $value);	// ³	
		$pattern = "/&supe;/";
		$value = preg_replace($pattern, "&#8839;", $value);	// ⊇	
		$pattern = "//";
		$value = preg_replace($pattern, "&#223;", $value);	// 	ß
		$pattern = "/&Tau;/";
		$value = preg_replace($pattern, "&#932;", $value);	// 	Τ
		$pattern = "/&tau;/";
		$value = preg_replace($pattern, "&#964;", $value);	// 	τ
		$pattern = "/&there4;/";
		$value = preg_replace($pattern, "&#8756;", $value);	// 	∴
		$pattern = "/&Theta;/";
		$value = preg_replace($pattern, "&#920;", $value);	// Θ	
		$pattern = "/&theta;/";
		$value = preg_replace($pattern, "&#952;", $value);	// 	θ
		$pattern = "/&thetasym;/";
		$value = preg_replace($pattern, "&#977;", $value);	// 	ϑ
		$pattern = "/&THORN;/";
		$value = preg_replace($pattern, "&#222;", $value);	// 	Þ
		$pattern = "/&thorn;/";
		$value = preg_replace($pattern, "&#254;", $value);	// þ	
		$pattern = "/&tilde;/";
		$value = preg_replace($pattern, "&#732;", $value);	// 	˜
		$pattern = "/&times;/";
		$value = preg_replace($pattern, "&#215;", $value);	// ×	
		$pattern = "/&trade;/";
		$value = preg_replace($pattern, "&#8482;", $value);	// ™	
		$pattern = "/&uacute;/";
		$value = preg_replace($pattern, "&#250;", $value);	// 	ú
		$pattern = "/&Uacute;/";
		$value = preg_replace($pattern, "&#218;", $value);	// 	Ú
		$pattern = "/&uArr;/";
		$value = preg_replace($pattern, "&#8657;", $value);	// 	⇑
		$pattern = "/&uarr;/";
		$value = preg_replace($pattern, "&#8593;", $value);	// 	↑
		$pattern = "/&ucirc;/";
		$value = preg_replace($pattern, "&#251;", $value);	// 	û
		$pattern = "/&Ucirc;/";
		$value = preg_replace($pattern, "&#219;", $value);	// 	Û
		$pattern = "/&Ugrave;/";
		$value = preg_replace($pattern, "&#217;", $value);	//  Ù	
		$pattern = "/&ugrave;/";
		$value = preg_replace($pattern, "&#249;", $value);	// 	ù
		$pattern = "/&uml;/";
		$value = preg_replace($pattern, "&#168;", $value);	// 	¨
		$pattern = "/&upsih;/";
		$value = preg_replace($pattern, "&#978;", $value);	// 	ϒ
		$pattern = "/&upsilon;/";
		$value = preg_replace($pattern, "&#965;", $value);	// 	υ
		$pattern = "/&Upsilon;/";
		$value = preg_replace($pattern, "&#933;", $value);	// 	Υ
		$pattern = "/&uuml;/";
		$value = preg_replace($pattern, "&#252;", $value);	// 	ü
		$pattern = "/&Uuml;/";
		$value = preg_replace($pattern, "&#220;", $value);	// 	Ü
		$pattern = "/&weierp;/";
		$value = preg_replace($pattern, "&#8472;", $value);	// 	℘
		$pattern = "/&xi;/";
		$value = preg_replace($pattern, "&#958;", $value);	// 	ξ
		$pattern = "/&Xi;/";
		$value = preg_replace($pattern, "&#926;", $value);	// 	Ξ
		$pattern = "/&yacute;/";
		$value = preg_replace($pattern, "&#253;", $value);	// 	ý
		$pattern = "/&Yacute;/";
		$value = preg_replace($pattern, "&#221;", $value);	// 	Ý
		$pattern = "/&yen;/";
		$value = preg_replace($pattern, "&#165;", $value);	// 	¥
		$pattern = "/&yuml;/";
		$value = preg_replace($pattern, "&#255;", $value);	// 	ÿ
		$pattern = "/&Yuml;/";
		$value = preg_replace($pattern, "&#376;", $value);	// 	Ÿ
		$pattern = "/&Zeta;/";
		$value = preg_replace($pattern, "&#918;", $value);	// 	Ζ
		$pattern = "/&zeta;/";
		$value = preg_replace($pattern, "&#950;", $value);	// 	ζ
	
	
	
	
		$pattern = "/&ccedil;/";
		$value = preg_replace($pattern, "&#231;", $value); // ç
		
		$pattern = "/&eacute;/";
		$value = preg_replace($pattern, "&#233;", $value); // é
		$pattern = "/&Eacute;/";
		$value = preg_replace($pattern, "&#201;", $value); // É
		$pattern = "/&Ecirc;/";
		$value = preg_replace($pattern, "&#202;", $value); // Ê
		$pattern = "/&ecirc;/";
		$value = preg_replace($pattern, "&#234;", $value); // ê
		$pattern = "/&egrave;/";
		$value = preg_replace($pattern, "&#232;", $value); // è
		$pattern = "/&Egrave;/";
		$value = preg_replace($pattern, "&#200;", $value); // È

		return $value;
	}
	*/
}
